-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["seahorse"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 10, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -17.5, 55  ,  1.5, 28  ,  37.5, -19  ,  40.5, 50  ,  19.5, 72  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 10, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1.5, 28  ,  -17.5, 55  ,  -17.5, 40  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 10, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -23.5, -64  ,  8.5, -72  ,  26.5, -60  ,  37.5, -19  ,  1.5, 28  ,  -23.5, 10  ,  -41.5, -38  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -17.5, 55  ,  1.5, 28  ,  37.5, -19  ,  40.5, 50  ,  19.5, 72  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1.5, 28  ,  -17.5, 55  ,  -17.5, 40  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -23.5, -64  ,  8.5, -72  ,  26.5, -60  ,  37.5, -19  ,  1.5, 28  ,  -23.5, 10  ,  -41.5, -38  }
                    }
                    
                    
                    
		}
		
		, 
		["ball"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   41, -9  ,  34, -30  ,  53, -28  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   27, 30  ,  38, 13  ,  47, 37  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -40, -12  ,  -38, 4  ,  -57, -6  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, -29  ,  -40, -12  ,  -52, -16  ,  -46, -39  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -38, 4  ,  -29, 28  ,  -42, 21  ,  -60, 9  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -42, 21  ,  -29, 28  ,  -46, 39  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1, 33  ,  22, 34  ,  6, 60  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -13, -57  ,  -11, -44  ,  -28, -29  ,  -39, -46  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2, -43  ,  -11, -44  ,  -7, -57  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   38, 13  ,  32, -4  ,  59, 12  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   8, -40  ,  22, 34  ,  -2, 28  ,  -2, -43  ,  2, -58  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -29, 28  ,  -18, 32  ,  -32, 48  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   34, -30  ,  16, -36  ,  48, -44  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -18, 32  ,  -2, 28  ,  -8, 36  ,  -24, 55  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   27, 30  ,  22, 34  ,  8, -40  ,  16, -36  ,  32, -4  ,  38, 13  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   41, -9  ,  32, -4  ,  16, -36  ,  34, -30  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   16, -36  ,  8, -40  ,  19, -58  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   22, 34  ,  27, 30  ,  36, 48  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, -29  ,  -11, -44  ,  -2, -43  ,  -2, 28  ,  -18, 32  ,  -29, 28  ,  -38, 4  ,  -40, -12  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   32, -4  ,  41, -9  ,  56, -8  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2, 28  ,  1, 33  ,  -2, 46  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -8, 36  ,  -2, 28  ,  -8, 58  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 7, friction = 100, bounce = 0.05, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2, 28  ,  22, 34  ,  1, 33  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

