//  This file was generated by LevelHelper
//  http://levelhelper.wordpress.com
//
//  LevelHelperLoader.mm - offline version
//  Created by Bogdan Vladu
//  Version 2.0
//  Copyright 2011 Bogdan Vladu. All rights reserved.
//  CURRENTLY ONLY ONLINE VERSION IS SUPPORTED FOR CHIPMUNK
