-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:397a8c9d946a8eaff3d677d602e0f9d5$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "rock_animations.swf/0000",
				spriteColorRect = { x = 234, y = 160, width = 82, height = 80 },
				textureRect = { x = 0, y = 0, width = 82, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0001",
				spriteColorRect = { x = 232, y = 156, width = 88, height = 84 },
				textureRect = { x = 82, y = 0, width = 88, height = 84 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0002",
				spriteColorRect = { x = 231, y = 154, width = 90, height = 86 },
				textureRect = { x = 170, y = 0, width = 90, height = 86 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0003",
				spriteColorRect = { x = 229, y = 153, width = 92, height = 88 },
				textureRect = { x = 260, y = 0, width = 92, height = 88 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0004",
				spriteColorRect = { x = 230, y = 153, width = 92, height = 88 },
				textureRect = { x = 352, y = 0, width = 92, height = 88 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0005",
				spriteColorRect = { x = 230, y = 153, width = 92, height = 88 },
				textureRect = { x = 0, y = 88, width = 92, height = 88 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0006",
				spriteColorRect = { x = 230, y = 153, width = 92, height = 88 },
				textureRect = { x = 92, y = 88, width = 92, height = 88 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0007",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 184, y = 88, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0008",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 278, y = 88, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0009",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 372, y = 88, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0010",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 0, y = 178, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0011",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 94, y = 178, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0012",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 188, y = 178, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0013",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 282, y = 178, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0014",
				spriteColorRect = { x = 227, y = 152, width = 96, height = 90 },
				textureRect = { x = 376, y = 178, width = 96, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0015",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 0, y = 268, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0016",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 94, y = 268, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0017",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 188, y = 268, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0018",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 282, y = 268, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0019",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 376, y = 268, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0020",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 0, y = 358, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0021",
				spriteColorRect = { x = 228, y = 152, width = 94, height = 90 },
				textureRect = { x = 94, y = 358, width = 94, height = 90 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0022",
				spriteColorRect = { x = 230, y = 153, width = 92, height = 88 },
				textureRect = { x = 188, y = 358, width = 92, height = 88 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0023",
				spriteColorRect = { x = 230, y = 153, width = 92, height = 88 },
				textureRect = { x = 280, y = 358, width = 92, height = 88 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0024",
				spriteColorRect = { x = 230, y = 153, width = 92, height = 88 },
				textureRect = { x = 372, y = 358, width = 92, height = 88 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0025",
				spriteColorRect = { x = 230, y = 153, width = 92, height = 88 },
				textureRect = { x = 0, y = 448, width = 92, height = 88 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0026",
				spriteColorRect = { x = 231, y = 154, width = 90, height = 86 },
				textureRect = { x = 92, y = 448, width = 90, height = 86 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0027",
				spriteColorRect = { x = 231, y = 154, width = 90, height = 86 },
				textureRect = { x = 182, y = 448, width = 90, height = 86 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0028",
				spriteColorRect = { x = 233, y = 156, width = 86, height = 84 },
				textureRect = { x = 272, y = 448, width = 86, height = 84 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0029",
				spriteColorRect = { x = 234, y = 160, width = 82, height = 80 },
				textureRect = { x = 0, y = 0, width = 82, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0030",
				spriteColorRect = { x = 234, y = 160, width = 82, height = 80 },
				textureRect = { x = 0, y = 0, width = 82, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

