-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:a9cf9758ef0e559c540730118af262b6$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "rock_animations.swf/0000",
				spriteColorRect = { x = 238, y = 161, width = 76, height = 70 },
				textureRect = { x = 257, y = 425, width = 76, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0001",
				spriteColorRect = { x = 236, y = 159, width = 80, height = 76 },
				textureRect = { x = 174, y = 425, width = 80, height = 76 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0002",
				spriteColorRect = { x = 235, y = 158, width = 82, height = 78 },
				textureRect = { x = 89, y = 425, width = 82, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0003",
				spriteColorRect = { x = 233, y = 157, width = 84, height = 80 },
				textureRect = { x = 2, y = 425, width = 84, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0004",
				spriteColorRect = { x = 233, y = 157, width = 84, height = 80 },
				textureRect = { x = 354, y = 340, width = 84, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0005",
				spriteColorRect = { x = 234, y = 157, width = 84, height = 80 },
				textureRect = { x = 267, y = 340, width = 84, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0006",
				spriteColorRect = { x = 234, y = 157, width = 84, height = 80 },
				textureRect = { x = 180, y = 340, width = 84, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0007",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 91, y = 340, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0008",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 2, y = 340, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0009",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 358, y = 255, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0010",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 269, y = 255, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0011",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 180, y = 255, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0012",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 91, y = 255, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0013",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 2, y = 255, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0014",
				spriteColorRect = { x = 230, y = 156, width = 88, height = 82 },
				textureRect = { x = 358, y = 170, width = 88, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0015",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 269, y = 170, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0016",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 180, y = 170, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0017",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 91, y = 170, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0018",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 2, y = 170, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0019",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 354, y = 85, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0020",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 265, y = 85, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0021",
				spriteColorRect = { x = 232, y = 156, width = 86, height = 82 },
				textureRect = { x = 176, y = 85, width = 86, height = 82 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0022",
				spriteColorRect = { x = 234, y = 157, width = 84, height = 80 },
				textureRect = { x = 89, y = 85, width = 84, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0023",
				spriteColorRect = { x = 234, y = 157, width = 84, height = 80 },
				textureRect = { x = 2, y = 85, width = 84, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0024",
				spriteColorRect = { x = 233, y = 157, width = 84, height = 80 },
				textureRect = { x = 344, y = 2, width = 84, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0025",
				spriteColorRect = { x = 233, y = 157, width = 84, height = 80 },
				textureRect = { x = 257, y = 2, width = 84, height = 80 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0026",
				spriteColorRect = { x = 233, y = 158, width = 84, height = 78 },
				textureRect = { x = 170, y = 2, width = 84, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0027",
				spriteColorRect = { x = 235, y = 158, width = 82, height = 78 },
				textureRect = { x = 85, y = 2, width = 82, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0028",
				spriteColorRect = { x = 236, y = 159, width = 80, height = 76 },
				textureRect = { x = 2, y = 2, width = 80, height = 76 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0029",
				spriteColorRect = { x = 238, y = 161, width = 76, height = 70 },
				textureRect = { x = 257, y = 425, width = 76, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_animations.swf/0030",
				spriteColorRect = { x = 238, y = 161, width = 76, height = 70 },
				textureRect = { x = 257, y = 425, width = 76, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

