-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:a316192887f05606c83e5c4afacd3c0a$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "rock_medium_animations.swf/0000",
				spriteColorRect = { x = 16, y = 16, width = 53, height = 53 },
				textureRect = { x = 0, y = 0, width = 53, height = 53 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0001",
				spriteColorRect = { x = 11, y = 10, width = 63, height = 63 },
				textureRect = { x = 53, y = 0, width = 63, height = 63 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0002",
				spriteColorRect = { x = 9, y = 9, width = 67, height = 65 },
				textureRect = { x = 116, y = 0, width = 67, height = 65 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0003",
				spriteColorRect = { x = 8, y = 8, width = 69, height = 67 },
				textureRect = { x = 183, y = 0, width = 69, height = 67 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0004",
				spriteColorRect = { x = 8, y = 8, width = 69, height = 67 },
				textureRect = { x = 252, y = 0, width = 69, height = 67 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0005",
				spriteColorRect = { x = 7, y = 7, width = 71, height = 69 },
				textureRect = { x = 321, y = 0, width = 71, height = 69 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0006",
				spriteColorRect = { x = 7, y = 7, width = 71, height = 69 },
				textureRect = { x = 392, y = 0, width = 71, height = 69 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0007",
				spriteColorRect = { x = 7, y = 7, width = 71, height = 69 },
				textureRect = { x = 0, y = 69, width = 71, height = 69 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0008",
				spriteColorRect = { x = 7, y = 7, width = 71, height = 69 },
				textureRect = { x = 71, y = 69, width = 71, height = 69 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0009",
				spriteColorRect = { x = 7, y = 7, width = 71, height = 69 },
				textureRect = { x = 142, y = 69, width = 71, height = 69 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0010",
				spriteColorRect = { x = 7, y = 6, width = 71, height = 71 },
				textureRect = { x = 213, y = 69, width = 71, height = 71 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0011",
				spriteColorRect = { x = 7, y = 6, width = 71, height = 71 },
				textureRect = { x = 284, y = 69, width = 71, height = 71 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0012",
				spriteColorRect = { x = 7, y = 6, width = 71, height = 71 },
				textureRect = { x = 355, y = 69, width = 71, height = 71 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0013",
				spriteColorRect = { x = 7, y = 6, width = 71, height = 71 },
				textureRect = { x = 426, y = 69, width = 71, height = 71 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0014",
				spriteColorRect = { x = 7, y = 6, width = 71, height = 71 },
				textureRect = { x = 0, y = 140, width = 71, height = 71 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0015",
				spriteColorRect = { x = 7, y = 6, width = 71, height = 71 },
				textureRect = { x = 426, y = 69, width = 71, height = 71 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0016",
				spriteColorRect = { x = 7, y = 6, width = 71, height = 71 },
				textureRect = { x = 355, y = 69, width = 71, height = 71 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0017",
				spriteColorRect = { x = 7, y = 6, width = 71, height = 71 },
				textureRect = { x = 71, y = 140, width = 71, height = 71 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0018",
				spriteColorRect = { x = 7, y = 6, width = 71, height = 71 },
				textureRect = { x = 142, y = 140, width = 71, height = 71 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0019",
				spriteColorRect = { x = 7, y = 7, width = 71, height = 69 },
				textureRect = { x = 213, y = 140, width = 71, height = 69 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0020",
				spriteColorRect = { x = 7, y = 7, width = 71, height = 69 },
				textureRect = { x = 284, y = 140, width = 71, height = 69 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0021",
				spriteColorRect = { x = 7, y = 7, width = 71, height = 69 },
				textureRect = { x = 355, y = 140, width = 71, height = 69 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0022",
				spriteColorRect = { x = 7, y = 7, width = 71, height = 69 },
				textureRect = { x = 426, y = 140, width = 71, height = 69 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0023",
				spriteColorRect = { x = 7, y = 7, width = 71, height = 69 },
				textureRect = { x = 0, y = 211, width = 71, height = 69 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0024",
				spriteColorRect = { x = 9, y = 7, width = 69, height = 69 },
				textureRect = { x = 71, y = 211, width = 69, height = 69 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0025",
				spriteColorRect = { x = 8, y = 8, width = 69, height = 67 },
				textureRect = { x = 140, y = 211, width = 69, height = 67 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0026",
				spriteColorRect = { x = 10, y = 8, width = 67, height = 67 },
				textureRect = { x = 209, y = 211, width = 67, height = 67 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0027",
				spriteColorRect = { x = 9, y = 9, width = 67, height = 65 },
				textureRect = { x = 276, y = 211, width = 67, height = 65 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0028",
				spriteColorRect = { x = 13, y = 11, width = 61, height = 61 },
				textureRect = { x = 343, y = 211, width = 61, height = 61 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0029",
				spriteColorRect = { x = 16, y = 16, width = 53, height = 53 },
				textureRect = { x = 0, y = 0, width = 53, height = 53 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_medium_animations.swf/0030",
				spriteColorRect = { x = 16, y = 16, width = 53, height = 53 },
				textureRect = { x = 0, y = 0, width = 53, height = 53 },
				spriteSourceSize = { width = 89, height = 89 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

