--[[
Spriteloq metadata
Generated by SpriteLoq: Loqheart's Flash SWF to sprite sheet Corona SDK exporter (c) Loqheart 2011
version 1.3.9
target Corona SDK
extension lua
exportName rocks_sheet
exportPath file:///Users/mwallace/Development/mobile/test
sheetSize 1805x1862
sources 1
name; url; referencePoint; startFrame; totalFrames; frameRate; topLeft; bottomRight; sourceRect; loopParam; xScale; yScale
fsr_animated_logo; ../assets/fsr/fsr_animated_logo.swf; (x=0, y=0); 1; 68; 15; (x=74, y=63); (x=433, y=194); (x=73, y=62, w=361, h=133); 0; 1; 1
assetShapes 0
]]

local sheet = false
local setInfo = false
local msFactor = 500  -- This should be 1000 ms. Corona BUG: The frame rate is playing back at around half speed at 30fps.

local function newSpriteSet(_sheet, _name, _startFrame, _frameCount, _frameRate, _loopParam, _xReference, _yReference, _spriteSourceWidth, _spriteSourceHeight, _unscaledSpriteX, _unscaledSpriteY, _unscaledSpriteWidth, _unscaledSpriteHeight, _frames, _shapeOnly)
    if (_shapeOnly) then
        return
    end

    local set = sprite.newSpriteSet(_sheet, _startFrame, _frameCount)
    sprite.add(set, _name, 1, _frameCount, (_frameCount / _frameRate) * msFactor, _loopParam)
    setInfo[_name] = {set = set, xReference = _xReference, yReference = _yReference, spriteSourceSize = {width = _spriteSourceWidth, height = _spriteSourceHeight}, unscaledSpriteRect = {x = _unscaledSpriteX, y = _unscaledSpriteY, width = _unscaledSpriteWidth, height = _unscaledSpriteHeight}, frames = _frames, frameRate = _frameRate, frameCount = _frameCount, fpss = _frameRate / 1000, startFrame = _startFrame}
end

local function load()
    local frameSets = {}
    local allFrames = {}

    frameSets["fsr_animated_logo"] = {
        {
            name="fsr_animated_logo-1",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=798, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-2",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=0, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-3",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=0, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-4",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=0, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-5",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=0, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-6",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=133, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-7",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=133, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-8",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=133, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-9",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=133, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-10",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=133, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-11",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=266, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-12",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=266, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-13",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=266, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-14",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=266, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-15",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=266, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-16",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=399, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-17",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=399, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-18",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=399, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-19",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=399, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-20",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=399, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-21",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=532, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-22",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=532, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-23",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=532, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-24",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=532, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-25",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=532, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-26",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=665, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-27",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=665, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-28",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=665, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-29",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=665, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-30",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=665, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-31",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=798, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-32",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=798, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-33",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=798, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-34",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=0, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-35",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=798, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-36",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=931, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-37",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=931, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-38",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=931, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-39",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=931, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-40",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=931, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-41",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1064, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-42",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=1064, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-43",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=1064, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-44",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=1064, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-45",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=1064, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-46",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1197, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-47",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=1197, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-48",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=1197, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-49",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=1197, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-50",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=1197, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-51",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1330, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-52",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=1330, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-53",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=1330, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-54",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=1330, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-55",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=1330, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-56",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1463, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-57",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=1463, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-58",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=1463, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-59",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=1463, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-60",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=1463, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-61",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1596, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-62",
            spriteColorRect={x=0, y=0},
            textureRect={x=361, y=1596, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-63",
            spriteColorRect={x=0, y=0},
            textureRect={x=722, y=1596, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-64",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=1596, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-65",
            spriteColorRect={x=0, y=0},
            textureRect={x=1444, y=1596, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-66",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1729, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-67",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=798, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        },
        {
            name="fsr_animated_logo-68",
            spriteColorRect={x=0, y=0},
            textureRect={x=1083, y=798, width=361, height=133},
            spriteSourceSize={width=361, height=133},
            spriteTrimmed=false,
        }
    }
    allFrames = table.copy(allFrames, frameSets["fsr_animated_logo"])


    sheet = sprite.newSpriteSheetFromData("rocks_logo.png", {frames = allFrames })

    -- setInfo table contains info about sprites: { (spriteName = {set: set, xReference: xReference, yReference: yReference, spriteSourceSize = {width: width, height: height}})+ }
    setInfo = {}
    newSpriteSet(sheet, "fsr_animated_logo", 1, 68, 15, 0, 0 - (361/2 + 73), 0 - (133/2 + 62), 361, 133, 0, 0, 361, 133, frameSets["fsr_animated_logo"], false)

    local shapes = {}
    shapes["fsr_animated_logo"] = {

    }

    return { sheet = sheet, setInfo = setInfo, shapes = shapes }
end

local function destroy()
    sheet:dispose()
    sheet = nil
    setInfo = nil
end

return { load = load, destroy = destroy }
