-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:007387a4dbe9ca3fd87835b2fb1ff8ee$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "shield_animation.swf/0000",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 0, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0001",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 0, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0002",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 0, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0003",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 0, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0004",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 0, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0005",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 0, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0006",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 0, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0007",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 0, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0008",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 0, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0009",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 0, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0010",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0011",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0012",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0013",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0014",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0015",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0016",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0017",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0018",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0019",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0020",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0021",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0022",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0023",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0024",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0025",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0026",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0027",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0028",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0029",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0030",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0031",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0032",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0033",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0034",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0035",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0036",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0037",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0038",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0039",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0040",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0041",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0042",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0043",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0044",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0045",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0046",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0047",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0048",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0049",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0050",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 500, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0051",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 500, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0052",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 500, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0053",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 500, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0054",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 500, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0055",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 500, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0056",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 500, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0057",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 500, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0058",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 500, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0059",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 500, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0060",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 600, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0061",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 600, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0062",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 600, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0063",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 600, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0064",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 600, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0065",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 600, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0066",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 600, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0067",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 600, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0068",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 600, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0069",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 600, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0070",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 700, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0071",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 700, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0072",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 700, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0073",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 700, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0074",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 700, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0075",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 700, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0076",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 700, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0077",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 700, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0078",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 700, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0079",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 700, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0080",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 800, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0081",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 800, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0082",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 800, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0083",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 800, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0084",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 800, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0085",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 800, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0086",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 800, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0087",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 800, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0088",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 800, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0089",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 800, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0090",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 900, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0091",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 900, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0092",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 900, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0093",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 900, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0094",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 900, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0095",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 900, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0096",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 900, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0097",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 900, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0098",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 900, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0099",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 900, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0100",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 1000, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0101",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 1000, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0102",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 1000, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0103",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 1000, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0104",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 1000, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0105",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 1000, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0106",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 1000, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0107",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 1000, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0108",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 1000, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0109",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 1000, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0110",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 1100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0111",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 1100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0112",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 1100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0113",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 1100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0114",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 1100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0115",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 1100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0116",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 1100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0117",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 1100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0118",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 1100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0119",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 1100, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0120",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 1200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0121",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 1200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0122",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 1200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0123",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 1200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0124",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 1200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0125",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 1200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0126",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 1200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0127",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 1200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0128",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 1200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0129",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 1200, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0130",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 1300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0131",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 1300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0132",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 1300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0133",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 1300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0134",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 1300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0135",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 1300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0136",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 1300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0137",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 1300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0138",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 1300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0139",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 1300, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0140",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 0, y = 1400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0141",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 100, y = 1400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0142",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 200, y = 1400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0143",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 300, y = 1400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0144",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 400, y = 1400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0145",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 500, y = 1400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0146",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 600, y = 1400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0147",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 700, y = 1400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0148",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 800, y = 1400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0149",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 1400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "shield_animation.swf/0150",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 900, y = 1400, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

