-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:12166ce36f1ea6df09349edbdd0a8cbc$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "rock_small_animations.swf/0000",
				spriteColorRect = { x = 16, y = 16, width = 35, height = 35 },
				textureRect = { x = 0, y = 0, width = 35, height = 35 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0001",
				spriteColorRect = { x = 9, y = 8, width = 51, height = 51 },
				textureRect = { x = 35, y = 0, width = 51, height = 51 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0002",
				spriteColorRect = { x = 7, y = 6, width = 55, height = 55 },
				textureRect = { x = 86, y = 0, width = 55, height = 55 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0003",
				spriteColorRect = { x = 6, y = 5, width = 57, height = 57 },
				textureRect = { x = 141, y = 0, width = 57, height = 57 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0004",
				spriteColorRect = { x = 6, y = 5, width = 57, height = 57 },
				textureRect = { x = 198, y = 0, width = 57, height = 57 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0005",
				spriteColorRect = { x = 5, y = 5, width = 59, height = 57 },
				textureRect = { x = 0, y = 57, width = 59, height = 57 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0006",
				spriteColorRect = { x = 5, y = 5, width = 59, height = 57 },
				textureRect = { x = 59, y = 57, width = 59, height = 57 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0007",
				spriteColorRect = { x = 5, y = 4, width = 59, height = 59 },
				textureRect = { x = 118, y = 57, width = 59, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0008",
				spriteColorRect = { x = 5, y = 4, width = 59, height = 59 },
				textureRect = { x = 177, y = 57, width = 59, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0009",
				spriteColorRect = { x = 5, y = 4, width = 59, height = 59 },
				textureRect = { x = 0, y = 116, width = 59, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0010",
				spriteColorRect = { x = 4, y = 4, width = 61, height = 59 },
				textureRect = { x = 59, y = 116, width = 61, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0011",
				spriteColorRect = { x = 4, y = 4, width = 61, height = 59 },
				textureRect = { x = 120, y = 116, width = 61, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0012",
				spriteColorRect = { x = 4, y = 4, width = 61, height = 59 },
				textureRect = { x = 181, y = 116, width = 61, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0013",
				spriteColorRect = { x = 4, y = 4, width = 61, height = 59 },
				textureRect = { x = 0, y = 175, width = 61, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0014",
				spriteColorRect = { x = 4, y = 4, width = 61, height = 59 },
				textureRect = { x = 61, y = 175, width = 61, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0015",
				spriteColorRect = { x = 4, y = 4, width = 61, height = 59 },
				textureRect = { x = 0, y = 175, width = 61, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0016",
				spriteColorRect = { x = 4, y = 4, width = 61, height = 59 },
				textureRect = { x = 181, y = 116, width = 61, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0017",
				spriteColorRect = { x = 4, y = 4, width = 61, height = 59 },
				textureRect = { x = 122, y = 175, width = 61, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0018",
				spriteColorRect = { x = 4, y = 4, width = 61, height = 59 },
				textureRect = { x = 183, y = 175, width = 61, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0019",
				spriteColorRect = { x = 5, y = 4, width = 59, height = 59 },
				textureRect = { x = 0, y = 234, width = 59, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0020",
				spriteColorRect = { x = 5, y = 4, width = 59, height = 59 },
				textureRect = { x = 59, y = 234, width = 59, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0021",
				spriteColorRect = { x = 5, y = 4, width = 59, height = 59 },
				textureRect = { x = 118, y = 234, width = 59, height = 59 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0022",
				spriteColorRect = { x = 5, y = 5, width = 59, height = 57 },
				textureRect = { x = 177, y = 234, width = 59, height = 57 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0023",
				spriteColorRect = { x = 5, y = 5, width = 59, height = 57 },
				textureRect = { x = 0, y = 293, width = 59, height = 57 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0024",
				spriteColorRect = { x = 5, y = 5, width = 59, height = 57 },
				textureRect = { x = 59, y = 293, width = 59, height = 57 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0025",
				spriteColorRect = { x = 6, y = 5, width = 57, height = 57 },
				textureRect = { x = 118, y = 293, width = 57, height = 57 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0026",
				spriteColorRect = { x = 6, y = 6, width = 57, height = 55 },
				textureRect = { x = 175, y = 293, width = 57, height = 55 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0027",
				spriteColorRect = { x = 7, y = 6, width = 55, height = 55 },
				textureRect = { x = 0, y = 350, width = 55, height = 55 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0028",
				spriteColorRect = { x = 10, y = 8, width = 49, height = 51 },
				textureRect = { x = 55, y = 350, width = 49, height = 51 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0029",
				spriteColorRect = { x = 16, y = 16, width = 35, height = 35 },
				textureRect = { x = 0, y = 0, width = 35, height = 35 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock_small_animations.swf/0030",
				spriteColorRect = { x = 16, y = 16, width = 35, height = 35 },
				textureRect = { x = 0, y = 0, width = 35, height = 35 },
				spriteSourceSize = { width = 71, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

