    -- Generated by Level Director v2.2.0 on 5/7/2013 9:21:04 PM

module(..., package.seeall)
require ("config")



imgSubFolder = ""
spriteSheets={}
spriteSets={}

if (application.LevelDirectorSettings.imagesSubfolder ~= nil) then
    imgSubFolder = application.LevelDirectorSettings.imagesSubfolder
    imgSubFolder = imgSubFolder .. "/"
end

function CreateLevel(physics)

    display.setDefault( 'background', 105,105,105 )
    physics.setGravity(0,0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "level2bBuild"
	
	---- Layer : bg ----
    level.layers["bg"] = display.newGroup()
    level.layers["bg"].name = "bg"

    level.layers["bg"].objects = {}
	
	level.layers["bg"].objects["river1"] = display.newImageRect( imgSubFolder .. "water.png", display.contentWidth, display.contentHeight)
    level.layers["bg"].objects["river1"].x = display.contentWidth/2
    level.layers["bg"].objects["river1"].y = 0
    level.layers["bg"].objects["river1"].name = "river1"
    level.layers["bg"]:insert(level.layers["bg"].objects["river1"])

    level.layers["bg"].objects["river2"] = display.newImageRect( imgSubFolder .. "water2.png", display.contentWidth, display.contentHeight)
    level.layers["bg"].objects["river2"].x = display.contentWidth/2
    level.layers["bg"].objects["river2"].y = display.contentHeight
    level.layers["bg"].objects["river2"].name = "river2"
    level.layers["bg"]:insert(level.layers["bg"].objects["river2"])

    level:insert(level.layers["bg"])

    ---- Layer : fg ----
    level.layers["fg"] = display.newGroup()
    level.layers["fg"].name = "fg"

    level.layers["fg"].objects = {}

    level.layers["fg"].objects["crushL"] = display.newImageRect( imgSubFolder .. "crusher.gif",169,298 )
    level.layers["fg"].objects["crushL"].x = 20
    level.layers["fg"].objects["crushL"].y = -3328
    local crushL_shape = {-44.5,-129,36.5,-130,43.5,133,-47.5,133    }
    physics.addBody(level.layers["fg"].objects["crushL"],"static",{density = 1, friction = 0, bounce = 0, shape = crushL_shape})
    level.layers["fg"].objects["crushL"].name = "crushL"
	level.layers["fg"].objects["crushL"].xInitial = 20
    level.layers["fg"].objects["crushL"].rotation = 270
    level.layers["fg"]:insert(level.layers["fg"].objects["crushL"])

    level.layers["fg"].objects["crushR"] = display.newImageRect( imgSubFolder .. "crusher.gif",169,298 )
    level.layers["fg"].objects["crushR"].x = 290
    level.layers["fg"].objects["crushR"].y = -3325
    local crushR_shape = {-44.5,-129,36.5,-130,43.5,133,-47.5,133    }
    physics.addBody(level.layers["fg"].objects["crushR"],"static",{density = 1, friction = 0, bounce = 0, shape = crushR_shape})
    level.layers["fg"].objects["crushR"].name = "crushR"
	level.layers["fg"].objects["crushR"].xInitial = 290
    level.layers["fg"].objects["crushR"].rotation = 90
    level.layers["fg"]:insert(level.layers["fg"].objects["crushR"])

	local whirl_png = sprite.newSpriteSheet( imgSubFolder .. "whirl.png", 165,170)
    local whirl_png_Set = sprite.newSpriteSet(whirl_png, 1,8)
    sprite.add(whirl_png_Set,"spin",1,8,500,0)
    level.layers["fg"].objects["whirl1"] = sprite.newSprite(whirl_png_Set)
    level.layers["fg"].objects["whirl1"].currentFrame = 1
    level.layers["fg"].objects["whirl1"].x = 242
    level.layers["fg"].objects["whirl1"].y = 77
    physics.addBody(level.layers["fg"].objects["whirl1"],"static",{density = 1, friction = 0, bounce = 0, radius = 80})
    level.layers["fg"].objects["whirl1"].name = "whirl1"
    level.layers["fg"]:insert(level.layers["fg"].objects["whirl1"])
	
    sprite.add(whirl_png_Set,"spin",1,8,500,0)
    level.layers["fg"].objects["whirl2"] = sprite.newSprite(whirl_png_Set)
    level.layers["fg"].objects["whirl2"].currentFrame = 1
    level.layers["fg"].objects["whirl2"].x = 82
    level.layers["fg"].objects["whirl2"].y = -131
    physics.addBody(level.layers["fg"].objects["whirl2"],"static",{density = 1, friction = 0, bounce = 0, radius = 80})
    level.layers["fg"].objects["whirl2"].name = "whirl2"
    level.layers["fg"]:insert(level.layers["fg"].objects["whirl2"])

    sprite.add(whirl_png_Set,"spin",1,8,500,0)
    level.layers["fg"].objects["whirl3"] = sprite.newSprite(whirl_png_Set)
    level.layers["fg"].objects["whirl3"].currentFrame = 1
    level.layers["fg"].objects["whirl3"].x = 242
    level.layers["fg"].objects["whirl3"].y = -307
    physics.addBody(level.layers["fg"].objects["whirl3"],"static",{density = 1, friction = 0, bounce = 0, radius = 80})
    level.layers["fg"].objects["whirl3"].name = "whirl3"
    level.layers["fg"]:insert(level.layers["fg"].objects["whirl3"])

    sprite.add(whirl_png_Set,"spin",1,8,500,0)
    level.layers["fg"].objects["whirl4"] = sprite.newSprite(whirl_png_Set)
    level.layers["fg"].objects["whirl4"].currentFrame = 1
    level.layers["fg"].objects["whirl4"].x = 250
    level.layers["fg"].objects["whirl4"].y = -942
    level.layers["fg"].objects["whirl4"].xScale = 2.06060606060606
    level.layers["fg"].objects["whirl4"].yScale = 2
    physics.addBody(level.layers["fg"].objects["whirl4"],"static",{density = 1, friction = 0, bounce = 0, radius = 170})
    level.layers["fg"].objects["whirl4"].name = "whirl4"
    level.layers["fg"]:insert(level.layers["fg"].objects["whirl4"])

    sprite.add(whirl_png_Set,"spin",1,8,500,0)
    level.layers["fg"].objects["whirl5"] = sprite.newSprite(whirl_png_Set)
    level.layers["fg"].objects["whirl5"].currentFrame = 1
    level.layers["fg"].objects["whirl5"].x = 90
    level.layers["fg"].objects["whirl5"].y = -1406
    level.layers["fg"].objects["whirl5"].xScale = 2.06060606060606
    level.layers["fg"].objects["whirl5"].yScale = 2
    physics.addBody(level.layers["fg"].objects["whirl5"],"static",{density = 1, friction = 0, bounce = 0, radius = 170})
    level.layers["fg"].objects["whirl5"].name = "whirl5"
    level.layers["fg"]:insert(level.layers["fg"].objects["whirl5"])

	
	local scaleFactor = 1.0
	local physicsData = (require "Level.turbine").physicsData(scaleFactor)
    level.layers["fg"].objects["turbineL"] = display.newImage( imgSubFolder .. "turbine.png")
	physics.addBody( level.layers["fg"].objects["turbineL"], "static", physicsData:get("Turbine") )
    level.layers["fg"].objects["turbineL"].x = 10
    level.layers["fg"].objects["turbineL"].y = -1976
    level.layers["fg"].objects["turbineL"].name = "turbineL"
    level.layers["fg"]:insert(level.layers["fg"].objects["turbineL"])

	level.layers["fg"].objects["turbineR"] = display.newImage( imgSubFolder .. "turbine.png" )
	physics.addBody( level.layers["fg"].objects["turbineR"], "static", physicsData:get("Turbine") )
    level.layers["fg"].objects["turbineR"].x = 310
    level.layers["fg"].objects["turbineR"].y = -1976
    level.layers["fg"].objects["turbineR"].name = "turbineR"
    level.layers["fg"].objects["turbineR"].rotation = 45
    level.layers["fg"]:insert(level.layers["fg"].objects["turbineR"])
	
	local eel_png = sprite.newSpriteSheet( imgSubFolder .. "eel.png", 84,38)
    local eel_png_Set = sprite.newSpriteSet(eel_png, 1,4)
    sprite.add(eel_png_Set,"eel",1,4,500,0)
    level.layers["fg"].objects["eel1"] = sprite.newSprite(eel_png_Set)
    level.layers["fg"].objects["eel1"].currentFrame = 1
    level.layers["fg"].objects["eel1"].x = 101
    level.layers["fg"].objects["eel1"].y = -555
    level.layers["fg"].objects["eel1"].xScale = 1.61904761904762
    level.layers["fg"].objects["eel1"].yScale = 1.97368421052632
    local eel1_shape = {-60.90434,-2.122635,27.79126,-9.198103,36.06963,-9.198103,64.45218,0.7075424,64.45218,7.783031,27.79126,24.76414,5.321754,24.76414,-59.72174,23.34906    }
    physics.addBody(level.layers["fg"].objects["eel1"],"static",{density = 1, friction = 0, bounce = 0, shape = eel1_shape})
    level.layers["fg"].objects["eel1"].name = "eel1"
    level.layers["fg"].objects["eel1"].rotation = 90
    level.layers["fg"]:insert(level.layers["fg"].objects["eel1"])

    sprite.add(eel_png_Set,"eel",1,4,500,0)
    level.layers["fg"].objects["eel2"] = sprite.newSprite(eel_png_Set)
    level.layers["fg"].objects["eel2"].currentFrame = 1
    level.layers["fg"].objects["eel2"].x = 262
    level.layers["fg"].objects["eel2"].y = -1692
    level.layers["fg"].objects["eel2"].xScale = 1.29761904761905
    level.layers["fg"].objects["eel2"].yScale = 1.47368421052632
    local eel2_shape = {-48.0119,-2.947365,23.35716,-5.894735,28.54761,-5.894735,50.60717,1.473684,50.60717,4.421047,22.0596,17.68422,5.190472,17.68422,-46.71428,14.73685    }
    physics.addBody(level.layers["fg"].objects["eel2"],"static",{density = 1, friction = 0, bounce = 0, shape = eel2_shape})
    level.layers["fg"].objects["eel2"].name = "eel2"
    level.layers["fg"].objects["eel2"].rotation = 90
    level.layers["fg"]:insert(level.layers["fg"].objects["eel2"])

    sprite.add(eel_png_Set,"eel",1,4,500,0)
    level.layers["fg"].objects["eel3"] = sprite.newSprite(eel_png_Set)
    level.layers["fg"].objects["eel3"].currentFrame = 1
    level.layers["fg"].objects["eel3"].x = 96
    level.layers["fg"].objects["eel3"].y = -2278
    level.layers["fg"].objects["eel3"].xScale = 1.52380952380952
    level.layers["fg"].objects["eel3"].yScale = 1.81578947368421
    local eel3_shape = {-56.38096,-3.631575,27.4286,-7.263145,33.52374,-7.263145,59.4286,1.815804,59.4286,5.447376,25.90466,21.78946,6.095276,21.78946,-54.85715,18.15789    }
    physics.addBody(level.layers["fg"].objects["eel3"],"static",{density = 1, friction = 0, bounce = 0, shape = eel3_shape})
    level.layers["fg"].objects["eel3"].name = "eel3"
    level.layers["fg"].objects["eel3"].rotation = 90
    level.layers["fg"]:insert(level.layers["fg"].objects["eel3"])

    sprite.add(eel_png_Set,"eel",1,4,500,0)
    level.layers["fg"].objects["eel4"] = sprite.newSprite(eel_png_Set)
    level.layers["fg"].objects["eel4"].currentFrame = 1
    level.layers["fg"].objects["eel4"].x = 224
    level.layers["fg"].objects["eel4"].y = -2422
    level.layers["fg"].objects["eel4"].xScale = 1.52380952380952
    level.layers["fg"].objects["eel4"].yScale = 1.81578947368421
    local eel4_shape = {-56,-3.5,27,-7.5,34,-7.5,59,1.5,59,5.5,26,21.5,6,21.5,-55,18.5    }
    physics.addBody(level.layers["fg"].objects["eel4"],"static",{density = 1, friction = 0, bounce = 0, shape = eel4_shape})
    level.layers["fg"].objects["eel4"].name = "eel4"
    level.layers["fg"].objects["eel4"].rotation = 90
    level.layers["fg"]:insert(level.layers["fg"].objects["eel4"])

    sprite.add(eel_png_Set,"eel",1,4,500,0)
    level.layers["fg"].objects["eel5"] = sprite.newSprite(eel_png_Set)
    level.layers["fg"].objects["eel5"].currentFrame = 1
    level.layers["fg"].objects["eel5"].x = 96
    level.layers["fg"].objects["eel5"].y = -2534
    level.layers["fg"].objects["eel5"].xScale = 1.52380952380952
    level.layers["fg"].objects["eel5"].yScale = 1.81578947368421
    local eel5_shape = {-56,-3.5,27,-7.5,34,-7.5,59,1.5,59,5.5,26,21.5,6,21.5,-55,18.5    }
    physics.addBody(level.layers["fg"].objects["eel5"],"static",{density = 1, friction = 0, bounce = 0, shape = eel5_shape})
    level.layers["fg"].objects["eel5"].name = "eel5"
    level.layers["fg"].objects["eel5"].rotation = 90
    level.layers["fg"]:insert(level.layers["fg"].objects["eel5"])

    sprite.add(eel_png_Set,"eel",1,4,500,0)
    level.layers["fg"].objects["eel6"] = sprite.newSprite(eel_png_Set)
    level.layers["fg"].objects["eel6"].currentFrame = 1
    level.layers["fg"].objects["eel6"].x = -26
    level.layers["fg"].objects["eel6"].y = -2683
    level.layers["fg"].objects["eel6"].xScale = 1.52380952380952
    level.layers["fg"].objects["eel6"].yScale = 1.81578947368421
    local eel6_shape = {-56,-3.5,27,-7.5,34,-7.5,59,1.5,59,5.5,26,21.5,6,21.5,-55,18.5    }
    physics.addBody(level.layers["fg"].objects["eel6"],"static",{density = 1, friction = 0, bounce = 0, shape = eel6_shape})
    level.layers["fg"].objects["eel6"].name = "eel6"
	level.layers["fg"].objects["eel6"].xInitial = -26
    level.layers["fg"]:insert(level.layers["fg"].objects["eel6"])

    sprite.add(eel_png_Set,"eel",1,4,500,0)
    level.layers["fg"].objects["eel7"] = sprite.newSprite(eel_png_Set)
    level.layers["fg"].objects["eel7"].currentFrame = 1
    level.layers["fg"].objects["eel7"].x = 322
    level.layers["fg"].objects["eel7"].y = -2844
    level.layers["fg"].objects["eel7"].xScale = 1.52380952380952
    level.layers["fg"].objects["eel7"].yScale = 1.81578947368421
    local eel7_shape = {-52,-20.5,60,-18.5,60,7.5,-52,10.5    }
    physics.addBody(level.layers["fg"].objects["eel7"],"static",{density = 1, friction = 0, bounce = 0, shape = eel7_shape})
    level.layers["fg"].objects["eel7"].name = "eel7"
    level.layers["fg"].objects["eel7"].rotation = 180
	level.layers["fg"].objects["eel7"].xInitial = 322
    level.layers["fg"]:insert(level.layers["fg"].objects["eel7"])

    sprite.add(eel_png_Set,"eel",1,4,500,0)
    level.layers["fg"].objects["eel8"] = sprite.newSprite(eel_png_Set)
    level.layers["fg"].objects["eel8"].currentFrame = 1
    level.layers["fg"].objects["eel8"].x = -26
    level.layers["fg"].objects["eel8"].y = -3001
    level.layers["fg"].objects["eel8"].xScale = 1.52380952380952
    level.layers["fg"].objects["eel8"].yScale = 1.81578947368421
    local eel8_shape = {-56,-3.5,27,-7.5,34,-7.5,59,1.5,59,5.5,26,21.5,6,21.5,-55,18.5    }
    physics.addBody(level.layers["fg"].objects["eel8"],"static",{density = 1, friction = 0, bounce = 0, shape = eel8_shape})
    level.layers["fg"].objects["eel8"].name = "eel8"
	level.layers["fg"].objects["eel8"].xInitial = -26
    level.layers["fg"]:insert(level.layers["fg"].objects["eel8"])
	
	local eelE_png = sprite.newSpriteSheet( imgSubFolder .. "eelE.png", 84,38)
    local eelE_png_Set = sprite.newSpriteSet(eelE_png, 1,4)
    sprite.add(eelE_png_Set,"eelE",1,4,500,0)
    level.layers["fg"].objects["eelE1"] = sprite.newSprite(eelE_png_Set)
    level.layers["fg"].objects["eelE1"].currentFrame = 1
    level.layers["fg"].objects["eelE1"].x = 101
    level.layers["fg"].objects["eelE1"].y = -555
    level.layers["fg"].objects["eelE1"].xScale = 1.61904761904762
    level.layers["fg"].objects["eelE1"].yScale = 1.97368421052632
    local eelE1_shape = {-60.90434,-2.122635,27.79126,-9.198103,36.06963,-9.198103,64.45218,0.7075424,64.45218,7.783031,27.79126,24.76414,5.321754,24.76414,-59.72174,23.34906    }
    physics.addBody(level.layers["fg"].objects["eelE1"],"static",{density = 1, friction = 0, bounce = 0, shape = eelE1_shape})
    level.layers["fg"].objects["eelE1"].name = "eelE1"
    level.layers["fg"].objects["eelE1"].rotation = 90
	level.layers["fg"].objects["eelE1"].isVisable = false
    level.layers["fg"]:insert(level.layers["fg"].objects["eelE1"])

    sprite.add(eelE_png_Set,"eelE",1,4,500,0)
    level.layers["fg"].objects["eelE2"] = sprite.newSprite(eelE_png_Set)
    level.layers["fg"].objects["eelE2"].currentFrame = 1
    level.layers["fg"].objects["eelE2"].x = 262
    level.layers["fg"].objects["eelE2"].y = -1692
    level.layers["fg"].objects["eelE2"].xScale = 1.29761904761905
    level.layers["fg"].objects["eelE2"].yScale = 1.47368421052632
    local eelE2_shape = {-48.0119,-2.947365,23.35716,-5.894735,28.54761,-5.894735,50.60717,1.473684,50.60717,4.421047,22.0596,17.68422,5.190472,17.68422,-46.71428,14.73685    }
    physics.addBody(level.layers["fg"].objects["eelE2"],"static",{density = 1, friction = 0, bounce = 0, shape = eelE2_shape})
    level.layers["fg"].objects["eelE2"].name = "eelE2"
    level.layers["fg"].objects["eelE2"].rotation = 90
	level.layers["fg"].objects["eelE2"].isVisable = false
    level.layers["fg"]:insert(level.layers["fg"].objects["eelE2"])

    sprite.add(eelE_png_Set,"eelE",1,4,500,0)
    level.layers["fg"].objects["eelE3"] = sprite.newSprite(eelE_png_Set)
    level.layers["fg"].objects["eelE3"].currentFrame = 1
    level.layers["fg"].objects["eelE3"].x = 96
    level.layers["fg"].objects["eelE3"].y = -2278
    level.layers["fg"].objects["eelE3"].xScale = 1.52380952380952
    level.layers["fg"].objects["eelE3"].yScale = 1.81578947368421
    local eelE3_shape = {-56.38096,-3.631575,27.4286,-7.263145,33.52374,-7.263145,59.4286,1.815804,59.4286,5.447376,25.90466,21.78946,6.095276,21.78946,-54.85715,18.15789    }
    physics.addBody(level.layers["fg"].objects["eelE3"],"static",{density = 1, friction = 0, bounce = 0, shape = eelE3_shape})
    level.layers["fg"].objects["eelE3"].name = "eelE3"
    level.layers["fg"].objects["eelE3"].rotation = 90
	level.layers["fg"].objects["eelE3"].isVisable = false
    level.layers["fg"]:insert(level.layers["fg"].objects["eelE3"])

    sprite.add(eelE_png_Set,"eelE",1,4,500,0)
    level.layers["fg"].objects["eelE4"] = sprite.newSprite(eelE_png_Set)
    level.layers["fg"].objects["eelE4"].currentFrame = 1
    level.layers["fg"].objects["eelE4"].x = 224
    level.layers["fg"].objects["eelE4"].y = -2422
    level.layers["fg"].objects["eelE4"].xScale = 1.52380952380952
    level.layers["fg"].objects["eelE4"].yScale = 1.81578947368421
    local eelE4_shape = {-56,-3.5,27,-7.5,34,-7.5,59,1.5,59,5.5,26,21.5,6,21.5,-55,18.5    }
    physics.addBody(level.layers["fg"].objects["eelE4"],"static",{density = 1, friction = 0, bounce = 0, shape = eelE4_shape})
    level.layers["fg"].objects["eelE4"].name = "eelE4"
    level.layers["fg"].objects["eelE4"].rotation = 90
	level.layers["fg"].objects["eelE4"].isVisable = false
    level.layers["fg"]:insert(level.layers["fg"].objects["eelE4"])

    sprite.add(eelE_png_Set,"eelE",1,4,500,0)
    level.layers["fg"].objects["eelE5"] = sprite.newSprite(eelE_png_Set)
    level.layers["fg"].objects["eelE5"].currentFrame = 1
    level.layers["fg"].objects["eelE5"].x = 96
    level.layers["fg"].objects["eelE5"].y = -2534
    level.layers["fg"].objects["eelE5"].xScale = 1.52380952380952
    level.layers["fg"].objects["eelE5"].yScale = 1.81578947368421
    local eelE5_shape = {-56,-3.5,27,-7.5,34,-7.5,59,1.5,59,5.5,26,21.5,6,21.5,-55,18.5    }
    physics.addBody(level.layers["fg"].objects["eelE5"],"static",{density = 1, friction = 0, bounce = 0, shape = eelE5_shape})
    level.layers["fg"].objects["eelE5"].name = "eelE5"
    level.layers["fg"].objects["eelE5"].rotation = 90
	level.layers["fg"].objects["eelE5"].isVisable = false
    level.layers["fg"]:insert(level.layers["fg"].objects["eelE5"])

    sprite.add(eelE_png_Set,"eelE",1,4,500,0)
    level.layers["fg"].objects["eelE6"] = sprite.newSprite(eelE_png_Set)
    level.layers["fg"].objects["eelE6"].currentFrame = 1
    level.layers["fg"].objects["eelE6"].x = -26
    level.layers["fg"].objects["eelE6"].y = -2683
    level.layers["fg"].objects["eelE6"].xScale = 1.52380952380952
    level.layers["fg"].objects["eelE6"].yScale = 1.81578947368421
    local eelE6_shape = {-56,-3.5,27,-7.5,34,-7.5,59,1.5,59,5.5,26,21.5,6,21.5,-55,18.5    }
    physics.addBody(level.layers["fg"].objects["eelE6"],"static",{density = 1, friction = 0, bounce = 0, shape = eelE6_shape})
    level.layers["fg"].objects["eelE6"].name = "eelE6"
	level.layers["fg"].objects["eelE6"].xInitial = -26
	level.layers["fg"].objects["eelE6"].isVisable = false
    level.layers["fg"]:insert(level.layers["fg"].objects["eelE6"])

    sprite.add(eelE_png_Set,"eelE",1,4,500,0)
    level.layers["fg"].objects["eelE7"] = sprite.newSprite(eelE_png_Set)
    level.layers["fg"].objects["eelE7"].currentFrame = 1
    level.layers["fg"].objects["eelE7"].x = 322
    level.layers["fg"].objects["eelE7"].y = -2844
    level.layers["fg"].objects["eelE7"].xScale = 1.52380952380952
    level.layers["fg"].objects["eelE7"].yScale = 1.81578947368421
    local eelE7_shape = {-52,-20.5,60,-18.5,60,7.5,-52,10.5    }
    physics.addBody(level.layers["fg"].objects["eelE7"],"static",{density = 1, friction = 0, bounce = 0, shape = eelE7_shape})
    level.layers["fg"].objects["eelE7"].name = "eelE7"
    level.layers["fg"].objects["eelE7"].rotation = 180
	level.layers["fg"].objects["eelE7"].xInitial = 322
	level.layers["fg"].objects["eelE7"].isVisable = false
    level.layers["fg"]:insert(level.layers["fg"].objects["eelE7"])

    sprite.add(eelE_png_Set,"eelE",1,4,500,0)
    level.layers["fg"].objects["eelE8"] = sprite.newSprite(eelE_png_Set)
    level.layers["fg"].objects["eelE8"].currentFrame = 1
    level.layers["fg"].objects["eelE8"].x = -26
    level.layers["fg"].objects["eelE8"].y = -3001
    level.layers["fg"].objects["eelE8"].xScale = 1.52380952380952
    level.layers["fg"].objects["eelE8"].yScale = 1.81578947368421
    local eelE8_shape = {-56,-3.5,27,-7.5,34,-7.5,59,1.5,59,5.5,26,21.5,6,21.5,-55,18.5    }
    physics.addBody(level.layers["fg"].objects["eelE8"],"static",{density = 1, friction = 0, bounce = 0, shape = eelE8_shape})
    level.layers["fg"].objects["eelE8"].name = "eelE8"
	level.layers["fg"].objects["eelE8"].xInitial = -26
	level.layers["fg"].objects["eelE8"].isVisable = false
    level.layers["fg"]:insert(level.layers["fg"].objects["eelE8"])
	
	level.layers["fg"].objects["finish"] = display.newImageRect( imgSubFolder .. "finish line.png",408,472 )
    level.layers["fg"].objects["finish"].x = 144
    level.layers["fg"].objects["finish"].y = -3627
    level.layers["fg"].objects["finish"].name = "finish"
    level.layers["fg"]:insert(level.layers["fg"].objects["finish"])

    level.layers["fg"].objects["pb15L"] = display.newImageRect( imgSubFolder .. "pb15L.png",100,2000 )
    level.layers["fg"].objects["pb15L"].x = -37
    level.layers["fg"].objects["pb15L"].y = -513
    local pb15L_shape = {-50,-999,-49,-1000,43,-1000,46,987,46,1000,-50,1000    }
    physics.addBody(level.layers["fg"].objects["pb15L"],"static",{density = 1, friction = 0, bounce = 0, shape = pb15L_shape})
    level.layers["fg"].objects["pb15L"].name = "pb15L"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb15L"])

    level.layers["fg"].objects["pb16L"] = display.newImageRect( imgSubFolder .. "pb16L.png",98,2025 )
    level.layers["fg"].objects["pb16L"].x = -38
    level.layers["fg"].objects["pb16L"].y = -2501
    local pb16L_shape = {-49,-1011.5,-48,-1012.5,44,-1012.5,45,-524.5,45,-151.5,45,987.5,-49,987.5    }
    physics.addBody(level.layers["fg"].objects["pb16L"],"static",{density = 1, friction = 0, bounce = 0, shape = pb16L_shape})
    level.layers["fg"].objects["pb16L"].name = "pb16L"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb16L"])

    level.layers["fg"].objects["pb17L"] = display.newImageRect( imgSubFolder .. "pb17L.png",93,362 )
    level.layers["fg"].objects["pb17L"].x = -41
    level.layers["fg"].objects["pb17L"].y = -3683
    physics.addBody(level.layers["fg"].objects["pb17L"],"static",{density = 1, friction = 0, bounce = 0})
    level.layers["fg"].objects["pb17L"].name = "pb17L"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb17L"])

    level.layers["fg"].objects["pb13R"] = display.newImageRect( imgSubFolder .. "pb13R.png",102,2000 )
    level.layers["fg"].objects["pb13R"].x = 348
    level.layers["fg"].objects["pb13R"].y = -510
    local pb13R_shape = {-46,979,-43,-1000,50,-1000,51,1000,-46,1000    }
    physics.addBody(level.layers["fg"].objects["pb13R"],"static",{density = 1, friction = 0, bounce = 0, shape = pb13R_shape})
    level.layers["fg"].objects["pb13R"].name = "pb13R"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb13R"])

    level.layers["fg"].objects["pb14R"] = display.newImageRect( imgSubFolder .. "pb14R.png",107,2057 )
    level.layers["fg"].objects["pb14R"].x = 346
    level.layers["fg"].objects["pb14R"].y = -2482
    local pb14R_shape = {-40.5,-1028.5,52.5,-1028.5,51.5,971.5,-40.5,971.5    }
    physics.addBody(level.layers["fg"].objects["pb14R"],"static",{density = 1, friction = 0, bounce = 0, shape = pb14R_shape})
    level.layers["fg"].objects["pb14R"].name = "pb14R"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb14R"])

    level.layers["fg"].objects["pb16R"] = display.newImageRect( imgSubFolder .. "pb15R.png",95,362 )
    level.layers["fg"].objects["pb16R"].x = 352
    level.layers["fg"].objects["pb16R"].y = -3681
    physics.addBody(level.layers["fg"].objects["pb16R"],"static",{density = 1, friction = 0, bounce = 0})
    level.layers["fg"].objects["pb16R"].name = "pb16R"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb16R"])

    level.layers["fg"].objects["pipe6"] = display.newImageRect( imgSubFolder .. "eelPipe.png",61,77 )
    level.layers["fg"].objects["pipe6"].x = 275
    level.layers["fg"].objects["pipe6"].y = -2997
    local pipe6_shape = {-30.5,-29.5,-4.5,-33.5,22.5,-33.5,22.5,-31.5,21.5,30.5,-4.5,30.5,-30.5,25.5    }
    physics.addBody(level.layers["fg"].objects["pipe6"],"static",{density = 1, friction = 0, bounce = 0, shape = pipe6_shape})
    level.layers["fg"].objects["pipe6"].name = "pipe6"
    level.layers["fg"].objects["pipe6"].rotation = 180
    level.layers["fg"]:insert(level.layers["fg"].objects["pipe6"])

    level.layers["fg"].objects["pipe5"] = display.newImageRect( imgSubFolder .. "eelPipe.png",61,77 )
    level.layers["fg"].objects["pipe5"].x = 33
    level.layers["fg"].objects["pipe5"].y = -2995
    local pipe5_shape = {-30.5,-29.5,-4.5,-33.5,22.5,-33.5,22.5,-31.5,21.5,30.5,-4.5,30.5,-30.5,25.5    }
    physics.addBody(level.layers["fg"].objects["pipe5"],"static",{density = 1, friction = 0, bounce = 0, shape = pipe5_shape})
    level.layers["fg"].objects["pipe5"].name = "pipe5"
    level.layers["fg"]:insert(level.layers["fg"].objects["pipe5"])

    level.layers["fg"].objects["pipe4"] = display.newImageRect( imgSubFolder .. "eelPipe.png",61,77 )
    level.layers["fg"].objects["pipe4"].x = 274
    level.layers["fg"].objects["pipe4"].y = -2838
    local pipe4_shape = {-30.5,-29.5,-4.5,-33.5,22.5,-33.5,22.5,-31.5,21.5,30.5,-4.5,30.5,-30.5,25.5    }
    physics.addBody(level.layers["fg"].objects["pipe4"],"static",{density = 1, friction = 0, bounce = 0, shape = pipe4_shape})
    level.layers["fg"].objects["pipe4"].name = "pipe4"
    level.layers["fg"].objects["pipe4"].rotation = 180
    level.layers["fg"]:insert(level.layers["fg"].objects["pipe4"])

    level.layers["fg"].objects["pipe3"] = display.newImageRect( imgSubFolder .. "eelPipe.png",61,77 )
    level.layers["fg"].objects["pipe3"].x = 32
    level.layers["fg"].objects["pipe3"].y = -2838
    local pipe3_shape = {-30.5,-29.5,-4.5,-33.5,22.5,-33.5,22.5,-31.5,21.5,30.5,-4.5,30.5,-30.5,25.5    }
    physics.addBody(level.layers["fg"].objects["pipe3"],"static",{density = 1, friction = 0, bounce = 0, shape = pipe3_shape})
    level.layers["fg"].objects["pipe3"].name = "pipe3"
    level.layers["fg"]:insert(level.layers["fg"].objects["pipe3"])

    level.layers["fg"].objects["pipe2"] = display.newImageRect( imgSubFolder .. "eelPipe.png",61,77 )
    level.layers["fg"].objects["pipe2"].x = 274
    level.layers["fg"].objects["pipe2"].y = -2679
    local pipe2_shape = {-30.5,-29.5,-4.5,-33.5,22.5,-33.5,22.5,-31.5,21.5,30.5,-4.5,30.5,-30.5,25.5    }
    physics.addBody(level.layers["fg"].objects["pipe2"],"static",{density = 1, friction = 0, bounce = 0, shape = pipe2_shape})
    level.layers["fg"].objects["pipe2"].name = "pipe2"
    level.layers["fg"].objects["pipe2"].rotation = 180
    level.layers["fg"]:insert(level.layers["fg"].objects["pipe2"])

    level.layers["fg"].objects["pipe1"] = display.newImageRect( imgSubFolder .. "eelPipe.png",61,77 )
    level.layers["fg"].objects["pipe1"].x = 36
    level.layers["fg"].objects["pipe1"].y = -2677
    local pipe1_shape = {-30.5,-29.5,-4.5,-33.5,22.5,-33.5,22.5,-31.5,21.5,30.5,-4.5,30.5,-30.5,25.5    }
    physics.addBody(level.layers["fg"].objects["pipe1"],"static",{density = 1, friction = 0, bounce = 0, shape = pipe1_shape})
    level.layers["fg"].objects["pipe1"].name = "pipe1"
    level.layers["fg"]:insert(level.layers["fg"].objects["pipe1"])
	
	level.layers["fg"].objects["redLine"] = display.newRect(-117,-3582,557,4)
    level.layers["fg"].objects["redLine"].strokeWidth = 1
    level.layers["fg"].objects["redLine"]:setFillColor(255,0,0 )
    level.layers["fg"].objects["redLine"]:setStrokeColor(255,0,0 )
    level.layers["fg"].objects["redLine"].name = "redLine"
    level.layers["fg"]:insert(level.layers["fg"].objects["redLine"])

    level.layers["fg"].objects["flag1"] = display.newImageRect( imgSubFolder .. "flag.gif",68,88 )
    level.layers["fg"].objects["flag1"].x = 22
    level.layers["fg"].objects["flag1"].y = -3623
    level.layers["fg"].objects["flag1"].name = "flag1"
    level.layers["fg"]:insert(level.layers["fg"].objects["flag1"])

    level.layers["fg"].objects["flag2"] = display.newImageRect( imgSubFolder .. "flag.gif",68,88 )
    level.layers["fg"].objects["flag2"].x = 312
    level.layers["fg"].objects["flag2"].y = -3622
    level.layers["fg"].objects["flag2"].name = "flag2"
    level.layers["fg"]:insert(level.layers["fg"].objects["flag2"])
	

    level:insert(level.layers["fg"])


    return level

end -- CreateLevel

