    -- Generated by Level Director v2.2.0 on 5/21/2013 10:52:55 PM

module(..., package.seeall)
require ("config")
require ("sprite")



imgSubFolder = ""
spriteSheets={}
spriteSets={}

if (application.LevelDirectorSettings.imagesSubfolder ~= nil) then
    imgSubFolder = application.LevelDirectorSettings.imagesSubfolder
    imgSubFolder = imgSubFolder .. "/"
end

function CreateLevel(physics)

    display.setDefault( 'background', 105,105,105 )
    physics.setGravity(0,0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "level2Build"

    ---- Layer : bg ----
    level.layers["bg"] = display.newGroup()
    level.layers["bg"].name = "bg"

    level.layers["bg"].objects = {}
	
	level.layers["bg"].objects["river1"] = display.newImageRect( imgSubFolder .. "water.png", display.contentWidth, display.contentHeight)
    level.layers["bg"].objects["river1"].x = display.contentWidth/2
    level.layers["bg"].objects["river1"].y = 0
    level.layers["bg"].objects["river1"].name = "river1"
    level.layers["bg"]:insert(level.layers["bg"].objects["river1"])

    level.layers["bg"].objects["river2"] = display.newImageRect( imgSubFolder .. "water2.png", display.contentWidth, display.contentHeight)
    level.layers["bg"].objects["river2"].x = display.contentWidth/2
    level.layers["bg"].objects["river2"].y = display.contentHeight
    level.layers["bg"].objects["river2"].name = "river2"
    level.layers["bg"]:insert(level.layers["bg"].objects["river2"])

    level:insert(level.layers["bg"])


    ---- Layer : fg ----
    level.layers["fg"] = display.newGroup()
    level.layers["fg"].name = "fg"

    level.layers["fg"].objects = {}

-- ===============================\/Swamps Sprites\/==========================================================
        local swampsSD = {
          { name = "normalRun", --name of animation sequence
          start = 1, --starting frame index
          count = 4, --total number of frames to animate consecutively before stopping or looping
          time = 1000, --optional, in milliseconds; if not supplied, the sprite is frame-based
          loopCount = 0, --optional. 0 (default) repeats forever; a positive integer specifies the number of loops
          loopDirection = "forward" --optional, either "forward" (default) or "bounce" which will play forward then backwards through the sequence of frames
          } --if defining more sequences, place a comma here and proceed to the next sequence sub-table
    }
    
    
        ---- Asset : swamp1 sprite ----
    local swamp1SI = require ("Scripts.swamp1")
    local swamp1Sheet = graphics.newImageSheet("Images/swamp1.png", swamp1SI:getSheet())
    local swamp1Anim = display.newSprite(swamp1Sheet, swampsSD)
    swamp1Anim.x = display.contentWidth/2
    swamp1Anim.y = -3533
    swamp1Anim.contentWidth = display.contentWidth
    level.layers["fg"].objects["swamp1"] = swamp1Anim
    level.layers["fg"]:insert(level.layers["fg"].objects["swamp1"])
    level.layers["fg"].objects["swamp1"].name = "swamp1"
    physics.addBody(level.layers["fg"].objects["swamp1"],"static",{density = 1, friction = 0, bounce = 0})
    
        ---- Asset : swamp2 sprite ----
    local swamp2SI = require ("Scripts.swamp2")
    local swamp2Sheet = graphics.newImageSheet("Images/swamp2.png", swamp2SI:getSheet())
    local swamp2Anim = display.newSprite(swamp2Sheet, swampsSD)
    swamp2Anim.x = 66
    swamp2Anim.y = -4287
    swamp2Anim.contentWidth = display.contentWidth
    level.layers["fg"].objects["swamp2"] = swamp2Anim
    level.layers["fg"]:insert(level.layers["fg"].objects["swamp2"])
    level.layers["fg"].objects["swamp2"].name = "swamp2"
    physics.addBody(level.layers["fg"].objects["swamp2"],"static",{density = 1, friction = 0, bounce = 0})

-- ===============================/\Swamps Sprites/\==========================================================
-- ===============================\/Rapids Sprites\/==========================================================
        local rapidsSD = {
          { name = "normalRun", --name of animation sequence
          start = 1, --starting frame index
          count = 15, --total number of frames to animate consecutively before stopping or looping
          time = 1000, --optional, in milliseconds; if not supplied, the sprite is frame-based
          loopCount = 0, --optional. 0 (default) repeats forever; a positive integer specifies the number of loops
          loopDirection = "forward" --optional, either "forward" (default) or "bounce" which will play forward then backwards through the sequence of frames
          } --if defining more sequences, place a comma here and proceed to the next sequence sub-table
    }
    
    
        ---- Asset : rapids1 sprite ----
    local rapids1SI = require ("Scripts.rapids1")
    local rapids1Sheet = graphics.newImageSheet("Images/rapids1.png", rapids1SI:getSheet())
    local rapids1Anim = display.newSprite(rapids1Sheet, rapidsSD)
    rapids1Anim.x = 160
    rapids1Anim.y = -1581
    rapids1Anim.contentWidth = display.contentWidth
    level.layers["fg"].objects["rapids1"] = rapids1Anim
    level.layers["fg"]:insert(level.layers["fg"].objects["rapids1"])
    level.layers["fg"].objects["rapids1"].name = "rapids1"
    physics.addBody(level.layers["fg"].objects["rapids1"],"static",{density = 1, friction = 0, bounce = 0})
    
            ---- Asset : rapids2 sprite ----
    local rapids2SI = require ("Scripts.rapids2")
    local rapids2Sheet = graphics.newImageSheet("Images/rapids2.png", rapids2SI:getSheet())
    local rapids2Anim = display.newSprite(rapids2Sheet, rapidsSD)
    rapids2Anim.x = 145
    rapids2Anim.y = -2538
    rapids2Anim.contentWidth = display.contentWidth
    level.layers["fg"].objects["rapids2"] = rapids2Anim
    level.layers["fg"]:insert(level.layers["fg"].objects["rapids2"])
    level.layers["fg"].objects["rapids2"].name = "rapids2"
    physics.addBody(level.layers["fg"].objects["rapids2"],"static",{density = 1, friction = 0, bounce = 0})
    
        ---- Asset : rapid3a sprite ----
    local rapids3aSI = require ("Scripts.rapidsPath1")
    local rapids3aSheet = graphics.newImageSheet("Images/rapidsPath1.png", rapids3aSI:getSheet())
    local rapids3aAnim = display.newSprite(rapids3aSheet, rapidsSD)
    rapids3aAnim.x = 162
    rapids3aAnim.y = -3077
    level.layers["fg"].objects["rapids3a"] = rapids3aAnim
    local rapids3a_shape = {-131,-38,-59,-95,-57,-96,18,-96,123,31,124,96,-130,96,-131,17    }
    physics.addBody(level.layers["fg"].objects["rapids3a"],"static",{density = 1, friction = 0, bounce = 0, shape = rapids3a_shape})
    rapids3aAnim.contentWidth = display.contentWidth
    level.layers["fg"]:insert(level.layers["fg"].objects["rapids3a"])
    level.layers["fg"].objects["rapids3a"].name = "rapids3a"
    
       

        ---- Asset : rapid3b sprite ----
    local rapids3bSI = require ("Scripts.rapidsPath2")
    local rapids3bSheet = graphics.newImageSheet("Images/rapidsPath2.png", rapids3bSI:getSheet())
    local rapids3bAnim = display.newSprite(rapids3bSheet, rapidsSD)
    rapids3bAnim.x = 175
    rapids3bAnim.y = -3278
    rapids3bAnim.contentWidth = display.contentWidth
    level.layers["fg"].objects["rapids3b"] = rapids3bAnim
    local rapids3b_shape = {-54,99,25,-115,84,-115,86,-93,86,-71,75,6,37,100,-54,100    }
    physics.addBody(level.layers["fg"].objects["rapids3b"],"static",{density = 1, friction = 0, bounce = 0, shape = rapids3b_shape})
    level.layers["fg"]:insert(level.layers["fg"].objects["rapids3b"])
    level.layers["fg"].objects["rapids3b"].name = "rapids3b"
    
    
            ---- Asset : rapid3c sprite ----
    local rapids3cSI = require ("Scripts.rapidsPath3")
    local rapids3cSheet = graphics.newImageSheet("Images/rapidsPath3.png", rapids3cSI:getSheet())
    local rapids3cAnim = display.newSprite(rapids3cSheet, rapidsSD)
    rapids3cAnim.x = 165
    rapids3cAnim.y = -3636
    rapids3cAnim.contentWidth = display.contentWidth
    level.layers["fg"].objects["rapids3c"] = rapids3cAnim
    local rapids3c_shape = {-54,-171.5,-26,-258.5,7,-258.5,63,246.5,23,246.5,-35,192.5,-68,126.5,-70,113.5    }
    physics.addBody(level.layers["fg"].objects["rapids3c"],"static",{density = 1, friction = 0, bounce = 0, shape = rapids3c_shape})
    level.layers["fg"]:insert(level.layers["fg"].objects["rapids3c"])
    level.layers["fg"].objects["rapids3c"].name = "rapids3c"
    physics.addBody(level.layers["fg"].objects["rapids3c"],"static",{density = 1, friction = 0, bounce = 0})

   
                ---- Asset : rapid3d sprite ----
    local rapids3dSI = require ("Scripts.rapidsPath4")
    local rapids3dSheet = graphics.newImageSheet("Images/rapidsPath4.png", rapids3dSI:getSheet())
    local rapids3dAnim = display.newSprite(rapids3dSheet, rapidsSD)
    rapids3dAnim.x = 212
    rapids3dAnim.y = -4116
    rapids3dAnim.contentWidth = display.contentWidth
    level.layers["fg"].objects["rapids3d"] = rapids3dAnim
    local rapids3d_shape = {-26,222.5,93,-231.5,111,-231.5,131,-164.5,131,-117.5,45,192.5,30,223.5,-26,223.5}
    for i=1, #rapids3d_shape do
       if (i % 2 == 1) then
          rapids3d_shape[i] = rapids3d_shape[i]-50
       end
    end
    physics.addBody(level.layers["fg"].objects["rapids3d"],"static",{density = 1, friction = 0, bounce = 0, shape = rapids3d_shape})
    level.layers["fg"]:insert(level.layers["fg"].objects["rapids3d"])
    level.layers["fg"].objects["rapids3d"].name = "rapids3d"
    physics.addBody(level.layers["fg"].objects["rapids3d"],"static",{density = 1, friction = 0, bounce = 0})

-- ===============================/\Rapids Sprites/\==========================================================



    level.layers["fg"].objects["beaveBoatH2"] = display.newImageRect( imgSubFolder .. "canoeH.png",108,39 )
    level.layers["fg"].objects["beaveBoatH2"].x = -15
    level.layers["fg"].objects["beaveBoatH2"].y = -65
    local beaveBoatH2_shape = {-54,-1.5,-3,-19.5,1,-19.5,53,0.5,53,2.5,9,19.5,-5,19.5,-54,-0.5    }
    physics.addBody(level.layers["fg"].objects["beaveBoatH2"],"static",{density = 2, friction = 0.2, bounce = 0.8, shape = beaveBoatH2_shape})
    level.layers["fg"].objects["beaveBoatH2"].name = "beaveBoatH2"
    level.layers["fg"]:insert(level.layers["fg"].objects["beaveBoatH2"])

    level.layers["fg"].objects["beaveBoatH4"] = display.newImageRect( imgSubFolder .. "canoeH.png",108,39 )
    level.layers["fg"].objects["beaveBoatH4"].x = -15
    level.layers["fg"].objects["beaveBoatH4"].y = -228
    local beaveBoatH4_shape = {-54,-1.5,-3,-19.5,1,-19.5,53,0.5,53,2.5,9,19.5,-5,19.5,-54,-0.5    }
    physics.addBody(level.layers["fg"].objects["beaveBoatH4"],"static",{density = 2, friction = 0.2, bounce = 0.8, shape = beaveBoatH4_shape})
    level.layers["fg"].objects["beaveBoatH4"].name = "beaveBoatH4"
    level.layers["fg"]:insert(level.layers["fg"].objects["beaveBoatH4"])

    level.layers["fg"].objects["beaveBoatV3"] = display.newImageRect( imgSubFolder .. "canoeV.png",51,139 )
    level.layers["fg"].objects["beaveBoatV3"].x = 255
    level.layers["fg"].objects["beaveBoatV3"].y = -365
    local beaveBoatV3_shape = {-25.5,-8.5,-1.5,-69.5,0.5,-69.5,24.5,-8.5,24.5,5.5,-0.5,69.5,-4.5,69.5,-25.5,10.5    }
    physics.addBody(level.layers["fg"].objects["beaveBoatV3"],"static",{density = 2, friction = 0.2, bounce = 0.8, shape = beaveBoatV3_shape})
    level.layers["fg"].objects["beaveBoatV3"].name = "beaveBoatV3"
    level.layers["fg"]:insert(level.layers["fg"].objects["beaveBoatV3"])

    level.layers["fg"].objects["beaveBoatV1"] = display.newImageRect( imgSubFolder .. "canoeV.png",51,139 )
    level.layers["fg"].objects["beaveBoatV1"].x = 46
    level.layers["fg"].objects["beaveBoatV1"].y = 61
    local beaveBoatV1_shape = {-25.5,-8.5,-1.5,-69.5,0.5,-69.5,24.5,-8.5,24.5,5.5,-0.5,69.5,-4.5,69.5,-25.5,10.5    }
    physics.addBody(level.layers["fg"].objects["beaveBoatV1"],"static",{density = 2, friction = 0.2, bounce = 0.8, shape = beaveBoatV1_shape})
    level.layers["fg"].objects["beaveBoatV1"].name = "beaveBoatV1"
    level.layers["fg"]:insert(level.layers["fg"].objects["beaveBoatV1"])

    level.layers["fg"].objects["beaveBoatV2"] = display.newImageRect( imgSubFolder .. "canoeV.png",51,139 )
    level.layers["fg"].objects["beaveBoatV2"].x = 277
    level.layers["fg"].objects["beaveBoatV2"].y = 64
    local beaveBoatV2_shape = {-25.5,-8.5,-1.5,-69.5,0.5,-69.5,24.5,-8.5,24.5,5.5,-0.5,69.5,-4.5,69.5,-25.5,10.5    }
    physics.addBody(level.layers["fg"].objects["beaveBoatV2"],"static",{density = 2, friction = 0.2, bounce = 0.8, shape = beaveBoatV2_shape})
    level.layers["fg"].objects["beaveBoatV2"].name = "beaveBoatV2"
    level.layers["fg"]:insert(level.layers["fg"].objects["beaveBoatV2"])

    level.layers["fg"].objects["pb1"] = display.newImageRect( imgSubFolder .. "pb1L.png",128,195 )
    level.layers["fg"].objects["pb1"].x = 32
    level.layers["fg"].objects["pb1"].y = -471
    local pb1_shape = {-57,-97.5,19,-97.5,30,-91.5,-17,63.5,-19,66.5,-30,72.5,-41,71.5,-57,67.5    }
    physics.addBody(level.layers["fg"].objects["pb1"],"static",{density = 1, friction = 0, bounce = 0, shape = pb1_shape})
    level.layers["fg"].objects["pb1"].name = "pb1"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb1"])

    level.layers["fg"].objects["pb2"] = display.newImageRect( imgSubFolder .. "pb2L.png",212,274 )
    level.layers["fg"].objects["pb2"].x = 74
    level.layers["fg"].objects["pb2"].y = -662
    local pb2_shape = {-99,-134,-49,-136,-29,-136,48,-124,85,-42,25,61,-13,99,-99,92    }
    physics.addBody(level.layers["fg"].objects["pb2"],"static",{density = 1, friction = 0, bounce = 0, shape = pb2_shape})
    level.layers["fg"].objects["pb2"].name = "pb2"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb2"])

    level.layers["fg"].objects["pb3"] = display.newImageRect( imgSubFolder .. "pb3L.png",166,251 )
    level.layers["fg"].objects["pb3"].x = 161
    level.layers["fg"].objects["pb3"].y = -779
    local pb3_shape = {-36,-3.5,30,-104.5,54,-106.5,75,-103.5,75,-67.5,25,44.5,-1,77.5,-40,5.5    }
    physics.addBody(level.layers["fg"].objects["pb3"],"static",{density = 1, friction = 0, bounce = 0, shape = pb3_shape})
    level.layers["fg"].objects["pb3"].name = "pb3"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb3"])

    level.layers["fg"].objects["pb4"] = display.newImageRect( imgSubFolder .. "pb4L.png",93,255 )
    level.layers["fg"].objects["pb4"].x = 14
    level.layers["fg"].objects["pb4"].y = -917
    local pb4_shape = {-39.5,-124.5,-30.5,-124.5,12.5,-123.5,15.5,-81.5,21.5,87.5,22.5,119.5,-34.5,122.5,-39.5,122.5    }
    physics.addBody(level.layers["fg"].objects["pb4"],"static",{density = 1, friction = 0, bounce = 0, shape = pb4_shape})
    level.layers["fg"].objects["pb4"].name = "pb4"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb4"])

    level.layers["fg"].objects["pb5"] = display.newImageRect( imgSubFolder .. "pb5L.png",282,261 )
    level.layers["fg"].objects["pb5"].x = 109
    level.layers["fg"].objects["pb5"].y = -1136
    local pb5_shape = {-134,-130.5,-26,-130.5,126,19.5,124,57.5,-56,93.5,-67,94.5,-121,95.5,-134,92.5    }
    physics.addBody(level.layers["fg"].objects["pb5"],"static",{density = 1, friction = 0, bounce = 0, shape = pb5_shape})
    level.layers["fg"].objects["pb5"].name = "pb5"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb5"])

    level.layers["fg"].objects["pb7"] = display.newImageRect( imgSubFolder .. "pb6L.png",125,110 )
    level.layers["fg"].objects["pb7"].x = 30
    level.layers["fg"].objects["pb7"].y = -1321
    local pb7_shape = {-55.5,-55,48.5,-55,46.5,54,-55.5,55    }
    physics.addBody(level.layers["fg"].objects["pb7"],"static",{density = 1, friction = 0, bounce = 0, shape = pb7_shape})
    level.layers["fg"].objects["pb7"].name = "pb7"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb7"])

    level.layers["fg"].objects["pb8"] = display.newImageRect( imgSubFolder .. "pb7L.png",151,203 )
    level.layers["fg"].objects["pb8"].x = 44
    level.layers["fg"].objects["pb8"].y = -1465
    local pb8_shape = {-68.5,-101.5,0.5,-101.5,68.5,21.5,68.5,25.5,64.5,46.5,54.5,67.5,36.5,89.5,-68.5,89.5    }
    physics.addBody(level.layers["fg"].objects["pb8"],"static",{density = 1, friction = 0, bounce = 0, shape = pb8_shape})
    level.layers["fg"].objects["pb8"].name = "pb8"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb8"])

    level.layers["fg"].objects["pb9"] = display.newImageRect( imgSubFolder .. "pb8L.png",70,1482 )
    level.layers["fg"].objects["pb9"].x = 3
    level.layers["fg"].objects["pb9"].y = -2301
    local pb9_shape = {-33,-474,-29,-740,27,-740,34,-362,35,734,-28,734,-31,138,-33,-471    }
    physics.addBody(level.layers["fg"].objects["pb9"],"static",{density = 1, friction = 0, bounce = 0, shape = pb9_shape})
    level.layers["fg"].objects["pb9"].name = "pb9"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb9"])

    level.layers["fg"].objects["pb10"] = display.newImageRect( imgSubFolder .. "pb9L.png",125,324 )
    level.layers["fg"].objects["pb10"].x = 146
    level.layers["fg"].objects["pb10"].y = -1778
    local pb10_shape = {-45.5,-57,-29.5,-154,4.5,-154,45.5,-56,45.5,31,36.5,141,-22.5,143,-43.5,75    }
    physics.addBody(level.layers["fg"].objects["pb10"],"static",{density = 1, friction = 0, bounce = 0, shape = pb10_shape})
    level.layers["fg"].objects["pb10"].name = "pb10"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb10"])

    level.layers["fg"].objects["pb11"] = display.newImageRect( imgSubFolder .. "pb10L.png",67,333 )
    level.layers["fg"].objects["pb11"].x = 2
    level.layers["fg"].objects["pb11"].y = -3207
    local pb11_shape = {-27.5,91.5,-25.5,-141.5,-0.5,-143.5,32.5,42.5,32.5,88.5,31.5,118.5,29.5,166.5,-27.5,166.5    }
    physics.addBody(level.layers["fg"].objects["pb11"],"static",{density = 1, friction = 0, bounce = 0, shape = pb11_shape})
    level.layers["fg"].objects["pb11"].name = "pb11"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb11"])

    level.layers["fg"].objects["pb12"] = display.newImageRect( imgSubFolder .. "pb11L.png",120,125 )
    level.layers["fg"].objects["pb12"].x = 88
    level.layers["fg"].objects["pb12"].y = -3177
    local pb12_shape = {-53,12.5,42,-55.5,49,-49.5,48,-22.5,-12,30.5,-43,52.5,-52,58.5,-53,58.5    }
    physics.addBody(level.layers["fg"].objects["pb12"],"static",{density = 1, friction = 0, bounce = 0, shape = pb12_shape})
    level.layers["fg"].objects["pb12"].name = "pb12"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb12"])

    level.layers["fg"].objects["pb13"] = display.newImageRect( imgSubFolder .. "pb12L.png",161,279 )
    level.layers["fg"].objects["pb13"].x = 48
    level.layers["fg"].objects["pb13"].y = -4123
    local pb13_shape = {-71.5,-139.5,-8.5,-139.5,71.5,-38.5,71.5,74.5,28.5,101.5,-47.5,139.5,-50.5,139.5,-71.5,130.5    }
    physics.addBody(level.layers["fg"].objects["pb13"],"static",{density = 1, friction = 0, bounce = 0, shape = pb13_shape})
    level.layers["fg"].objects["pb13"].name = "pb13"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb13"])

    level.layers["fg"].objects["pb14"] = display.newImageRect( imgSubFolder .. "pb13L.png",78,550 )
    level.layers["fg"].objects["pb14"].x = 7
    level.layers["fg"].objects["pb14"].y = -4536
    local pb14_shape = {-30,-275,38,-275,34,196,28,274,-30,274    }
    physics.addBody(level.layers["fg"].objects["pb14"],"static",{density = 1, friction = 0, bounce = 0, shape = pb14_shape})
    level.layers["fg"].objects["pb14"].name = "pb14"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb14"])

    level.layers["fg"].objects["pb15"] = display.newImageRect( imgSubFolder .. "pb14L.png",106,622 )
    level.layers["fg"].objects["pb15"].x = 87
    level.layers["fg"].objects["pb15"].y = -4506
    local pb15_shape = {-53,-309,8,-309,36,70,50,305,49,305,22,254,-42,130,-53,-307    }
    physics.addBody(level.layers["fg"].objects["pb15"],"static",{density = 1, friction = 0, bounce = 0, shape = pb15_shape})
    level.layers["fg"].objects["pb15"].name = "pb15"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb15"])

    level.layers["fg"].objects["pb16"] = display.newImageRect( imgSubFolder .. "pb1R.png",176,455 )
    level.layers["fg"].objects["pb16"].x = 275
    level.layers["fg"].objects["pb16"].y = -581
    local pb16_shape = {-59,19.5,17,-205.5,49,-224.5,52,-224.5,52,179.5,47,215.5,44,215.5,-59,20.5    }
    physics.addBody(level.layers["fg"].objects["pb16"],"static",{density = 1, friction = 0, bounce = 0, shape = pb16_shape})
    level.layers["fg"].objects["pb16"].name = "pb16"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb16"])

    level.layers["fg"].objects["pb17"] = display.newImageRect( imgSubFolder .. "pb2R.png",65,496 )
    level.layers["fg"].objects["pb17"].x = 303
    level.layers["fg"].objects["pb17"].y = -1016
    local pb17_shape = {-32.5,-247,-30.5,-248,23.5,-248,23.5,210,19.5,213,-19.5,237,-20.5,237,-29.5,-55    }
    physics.addBody(level.layers["fg"].objects["pb17"],"static",{density = 1, friction = 0, bounce = 0, shape = pb17_shape})
    level.layers["fg"].objects["pb17"].name = "pb17"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb17"])

    level.layers["fg"].objects["pb18"] = display.newImageRect( imgSubFolder .. "pb3R.png",144,125 )
    level.layers["fg"].objects["pb18"].x = 206
    level.layers["fg"].objects["pb18"].y = -975
    local pb18_shape = {-72,-41.5,70,-57.5,71,53.5,-72,58.5    }
    physics.addBody(level.layers["fg"].objects["pb18"],"static",{density = 1, friction = 0, bounce = 0, shape = pb18_shape})
    level.layers["fg"].objects["pb18"].name = "pb18"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb18"])

    level.layers["fg"].objects["pb19"] = display.newImageRect( imgSubFolder .. "pb4R.png",81,196 )
    level.layers["fg"].objects["pb19"].x = 106
    level.layers["fg"].objects["pb19"].y = -928
    local pb19_shape = {-26.5,-49,2.5,-88,37.5,-89,37.5,16,37.5,18,11.5,93,8.5,93,-34.5,19    }
    physics.addBody(level.layers["fg"].objects["pb19"],"static",{density = 1, friction = 0, bounce = 0, shape = pb19_shape})
    level.layers["fg"].objects["pb19"].name = "pb19"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb19"])

    level.layers["fg"].objects["pb20"] = display.newImageRect( imgSubFolder .. "pb5R.png",138,158 )
    level.layers["fg"].objects["pb20"].x = 219
    level.layers["fg"].objects["pb20"].y = -1185
    local pb20_shape = {-46,-79,52,-79,53,50,52,50,46,44,-38,-65,-41,-69,-43,-72    }
    physics.addBody(level.layers["fg"].objects["pb20"],"static",{density = 1, friction = 0, bounce = 0, shape = pb20_shape})
    level.layers["fg"].objects["pb20"].name = "pb20"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb20"])

    level.layers["fg"].objects["pb21"] = display.newImageRect( imgSubFolder .. "pb6R.png",223,361 )
    level.layers["fg"].objects["pb21"].x = 223
    level.layers["fg"].objects["pb21"].y = -1445
    local pb21_shape = {-103.5,119.5,70.5,-180.5,104.5,-180.5,105.5,180.5,-50.5,180.5,-97.5,136.5,-102.5,125.5,-103.5,122.5    }
    physics.addBody(level.layers["fg"].objects["pb21"],"static",{density = 1, friction = 0, bounce = 0, shape = pb21_shape})
    level.layers["fg"].objects["pb21"].name = "pb21"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb21"])

    level.layers["fg"].objects["pb22"] = display.newImageRect( imgSubFolder .. "pb7R.png",64,1427 )
    level.layers["fg"].objects["pb22"].x = 307
    level.layers["fg"].objects["pb22"].y = -2326
    local pb22_shape = {-24,134.5,-21,-712.5,20,-712.5,25,-446.5,25,-443.5,21,701.5,-14,701.5,-24,167.5    }
    physics.addBody(level.layers["fg"].objects["pb22"],"static",{density = 1, friction = 0, bounce = 0, shape = pb22_shape})
    level.layers["fg"].objects["pb22"].name = "pb22"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb22"])

    level.layers["fg"].objects["pb23"] = display.newImageRect( imgSubFolder .. "pb9R.png",119,133 )
    level.layers["fg"].objects["pb23"].x = 222
    level.layers["fg"].objects["pb23"].y = -3106
    local pb23_shape = {-59.5,-41.5,-32.5,-50.5,49.5,26.5,49.5,59.5,39.5,63.5,32.5,63.5,-58.5,-26.5,-59.5,-34.5    }
    physics.addBody(level.layers["fg"].objects["pb23"],"static",{density = 1, friction = 0, bounce = 0, shape = pb23_shape})
    level.layers["fg"].objects["pb23"].name = "pb23"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb23"])

    level.layers["fg"].objects["pb24"] = display.newImageRect( imgSubFolder .. "pb10R.png",108,330 )
    level.layers["fg"].objects["pb24"].x = 298
    level.layers["fg"].objects["pb24"].y = -4088
    local pb24_shape = {-47,-76,-7,-165,43,-165,44,165,19,165,-48,48,-50,41,-51,35    }
    physics.addBody(level.layers["fg"].objects["pb24"],"static",{density = 1, friction = 0, bounce = 0, shape = pb24_shape})
    level.layers["fg"].objects["pb24"].name = "pb24"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb24"])

    level.layers["fg"].objects["pb25"] = display.newImageRect( imgSubFolder .. "pb11R.png",71,572 )
    level.layers["fg"].objects["pb25"].x = 314
    level.layers["fg"].objects["pb25"].y = -4529
    local pb25_shape = {-35.5,-284,27.5,-284,28.5,277,-22.5,277,-35.5,190    }
    physics.addBody(level.layers["fg"].objects["pb25"],"static",{density = 1, friction = 0, bounce = 0, shape = pb25_shape})
    level.layers["fg"].objects["pb25"].name = "pb25"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb25"])

    level.layers["fg"].objects["pb26"] = display.newImageRect( imgSubFolder .. "pb12R.png",96,650 )
    level.layers["fg"].objects["pb26"].x = 240
    level.layers["fg"].objects["pb26"].y = -4489
    local pb26_shape = {-23,-323,37,-323,37,149,-26,281,-27,283,-29,286,-48,299,-39,56    }
    physics.addBody(level.layers["fg"].objects["pb26"],"static",{density = 1, friction = 0, bounce = 0, shape = pb26_shape})
    level.layers["fg"].objects["pb26"].name = "pb26"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb26"])

    level.layers["fg"].objects["pb27"] = display.newImageRect( imgSubFolder .. "pbMedRock.png",174,107 )
    level.layers["fg"].objects["pb27"].x = 233
    level.layers["fg"].objects["pb27"].y = -2500
    local pb27_shape = {-17,-41.5,83,-34.5,84,-19.5,86,37.5,-4,44.5,-74,13.5,-77,10.5,-84,-18.5    }
    physics.addBody(level.layers["fg"].objects["pb27"],"static",{density = 1, friction = 0, bounce = 0, shape = pb27_shape})
    level.layers["fg"].objects["pb27"].name = "pb27"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb27"])

    level.layers["fg"].objects["pb28"] = display.newImageRect( imgSubFolder .. "pbMedRock.png",174,107 )
    level.layers["fg"].objects["pb28"].x = 92
    level.layers["fg"].objects["pb28"].y = -2329
    local pb28_shape = {-77,-26.5,-13,-45.5,86,-33.5,86,37.5,-3,44.5,-74,13.5,-77,10.5,-84,-0.5    }
    physics.addBody(level.layers["fg"].objects["pb28"],"static",{density = 1, friction = 0, bounce = 0, shape = pb28_shape})
    level.layers["fg"].objects["pb28"].name = "pb28"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb28"])

    level.layers["fg"].objects["pb29"] = display.newImageRect( imgSubFolder .. "pbSmallRock.png",108,87 )
    level.layers["fg"].objects["pb29"].x = 42
    level.layers["fg"].objects["pb29"].y = -2163
    local pb29_shape = {-54,-9.5,-17,-31.5,17,-31.5,40,-22.5,49,26.5,14,38.5,-5,38.5,-54,2.5    }
    physics.addBody(level.layers["fg"].objects["pb29"],"static",{density = 1, friction = 0, bounce = 0, shape = pb29_shape})
    level.layers["fg"].objects["pb29"].name = "pb29"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb29"])

    level.layers["fg"].objects["pb30"] = display.newImageRect( imgSubFolder .. "pbSmallRock.png",108,87 )
    level.layers["fg"].objects["pb30"].x = 258
    level.layers["fg"].objects["pb30"].y = -2164
    local pb30_shape = {-54,-9.5,-17,-31.5,17,-31.5,39,-20.5,49,26.5,14,38.5,-5,38.5,-54,2.5    }
    physics.addBody(level.layers["fg"].objects["pb30"],"static",{density = 1, friction = 0, bounce = 0, shape = pb30_shape})
    level.layers["fg"].objects["pb30"].name = "pb30"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb30"])

    level.layers["fg"].objects["pb31"] = display.newImageRect( imgSubFolder .. "pbSmallRock.png",108,87 )
    level.layers["fg"].objects["pb31"].x = 48
    level.layers["fg"].objects["pb31"].y = -2631
    local pb31_shape = {-54,-9.5,-17,-31.5,17,-31.5,40,-17.5,49,26.5,14,38.5,-5,38.5,-54,2.5    }
    physics.addBody(level.layers["fg"].objects["pb31"],"static",{density = 1, friction = 0, bounce = 0, shape = pb31_shape})
    level.layers["fg"].objects["pb31"].name = "pb31"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb31"])

    level.layers["fg"].objects["pb32"] = display.newImageRect( imgSubFolder .. "pbSmallRock.png",108,87 )
    level.layers["fg"].objects["pb32"].x = 101
    level.layers["fg"].objects["pb32"].y = -2704
    local pb32_shape = {-54,-9.5,-17,-31.5,17,-31.5,42,-16.5,49,26.5,14,38.5,-5,38.5,-54,2.5    }
    physics.addBody(level.layers["fg"].objects["pb32"],"static",{density = 1, friction = 0, bounce = 0, shape = pb32_shape})
    level.layers["fg"].objects["pb32"].name = "pb32"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb32"])

    level.layers["fg"].objects["pb33"] = display.newImageRect( imgSubFolder .. "pbSmallRock.png",108,87 )
    level.layers["fg"].objects["pb33"].x = 170
    level.layers["fg"].objects["pb33"].y = -2781
    local pb33_shape = {-54,-9.5,-17,-31.5,17,-31.5,41,-18.5,49,26.5,14,38.5,-5,38.5,-54,2.5    }
    physics.addBody(level.layers["fg"].objects["pb33"],"static",{density = 1, friction = 0, bounce = 0, shape = pb33_shape})
    level.layers["fg"].objects["pb33"].name = "pb33"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb33"])

    level.layers["fg"].objects["pb34"] = display.newImageRect( imgSubFolder .. "pb8R.png",67,312 )
    level.layers["fg"].objects["pb34"].x = 306
    level.layers["fg"].objects["pb34"].y = -3194
    local pb34_shape = {-33.5,116,8.5,-153,13.5,-156,15.5,-156,21.5,-153,22.5,156,-19.5,156,-33.5,149    }
    physics.addBody(level.layers["fg"].objects["pb34"],"static",{density = 1, friction = 0, bounce = 0, shape = pb34_shape})
    level.layers["fg"].objects["pb34"].name = "pb34"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb34"])

    level.layers["fg"].objects["pb35"] = display.newImageRect( imgSubFolder .. "pbEndPipe.png",108,402 )
    level.layers["fg"].objects["pb35"].x = 150
    level.layers["fg"].objects["pb35"].y = -4613
    local pb35_shape = {-54,-199,53,-201,53,-168,-54,-167    }
    physics.addBody(level.layers["fg"].objects["pb35"],"static",{density = 1, friction = 0, bounce = 0, shape = pb35_shape})
    level.layers["fg"].objects["pb35"].name = "pb35"
    level.layers["fg"]:insert(level.layers["fg"].objects["pb35"])
	
	level.layers["fg"].objects["info"] = display.newImageRect( imgSubFolder .. "infoSign.gif",120,63 )
    level.layers["fg"].objects["info"].x = 60
    level.layers["fg"].objects["info"].y = 300
    level.layers["fg"].objects["info"].name = "info"
	level.layers["fg"].objects["info"].alpha = .75
    level.layers["fg"]:insert(level.layers["fg"].objects["info"])

    level.layers["fg"].objects["beave1"] = display.newImageRect( imgSubFolder .. "theBeave.png",40,56 )
    level.layers["fg"].objects["beave1"].x = 148
    level.layers["fg"].objects["beave1"].y = -748
    level.layers["fg"].objects["beave1"].name = "beave1"
    level.layers["fg"]:insert(level.layers["fg"].objects["beave1"])

    level.layers["fg"].objects["beave2"] = display.newImageRect( imgSubFolder .. "theBeave.png",40,56 )
    level.layers["fg"].objects["beave2"].x = 119
    level.layers["fg"].objects["beave2"].y = -954
    level.layers["fg"].objects["beave2"].name = "beave2"
    level.layers["fg"]:insert(level.layers["fg"].objects["beave2"])

    level.layers["fg"].objects["beave3"] = display.newImageRect( imgSubFolder .. "theBeave.png",40,56 )
    level.layers["fg"].objects["beave3"].x = 161
    level.layers["fg"].objects["beave3"].y = -1109
    level.layers["fg"].objects["beave3"].name = "beave3"
    level.layers["fg"]:insert(level.layers["fg"].objects["beave3"])

    level.layers["fg"].objects["beave4"] = display.newImageRect( imgSubFolder .. "theBeave.png",40,56 )
    level.layers["fg"].objects["beave4"].x = 200
    level.layers["fg"].objects["beave4"].y = -1329
    level.layers["fg"].objects["beave4"].name = "beave4"
    level.layers["fg"]:insert(level.layers["fg"].objects["beave4"])

    level.layers["fg"].objects["beave5"] = display.newImageRect( imgSubFolder .. "theBeave.png",40,56 )
    level.layers["fg"].objects["beave5"].x = 148
    level.layers["fg"].objects["beave5"].y = -1735
    level.layers["fg"].objects["beave5"].name = "beave5"
    level.layers["fg"]:insert(level.layers["fg"].objects["beave5"])

    level.layers["fg"].objects["beave6"] = display.newImageRect( imgSubFolder .. "theBeave.png",40,56 )
    level.layers["fg"].objects["beave6"].x = 143
    level.layers["fg"].objects["beave6"].y = -1836
    level.layers["fg"].objects["beave6"].name = "beave6"
    level.layers["fg"]:insert(level.layers["fg"].objects["beave6"])

    level.layers["fg"].objects["lWall"] = display.newRect(-21,-2,22,482)
    level.layers["fg"].objects["lWall"].strokeWidth = 1
    level.layers["fg"].objects["lWall"]:setFillColor(255,255,255 )
    physics.addBody(level.layers["fg"].objects["lWall"],"static",{density = 1, friction = 0, bounce = 0})
    level.layers["fg"].objects["lWall"].name = "lWall"
    level.layers["fg"]:insert(level.layers["fg"].objects["lWall"])

    level.layers["fg"].objects["rWall"] = display.newRect(320,-2,22,482)
    level.layers["fg"].objects["rWall"].strokeWidth = 1
    level.layers["fg"].objects["rWall"]:setFillColor(255,255,255 )
    physics.addBody(level.layers["fg"].objects["rWall"],"static",{density = 1, friction = 0, bounce = 0})
    level.layers["fg"].objects["rWall"].name = "rWall"
    level.layers["fg"]:insert(level.layers["fg"].objects["rWall"])

    level:insert(level.layers["fg"])


    return level

end -- CreateLevel

