module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- For more details, see http://developer.anscamobile.com/reference/sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "b1.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 27 }, 
				textureRect = { x = 0, y = 0, width = 31, height = 27 }, 
				spriteSourceSize = { width = 31, height = 27 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b2.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 31 }, 
				textureRect = { x = 33, y = 0, width = 27, height = 31 }, 
				spriteSourceSize = { width = 27, height = 31 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b3.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 27 }, 
				textureRect = { x = 62, y = 0, width = 31, height = 27 }, 
				spriteSourceSize = { width = 31, height = 27 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b4.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 31 }, 
				textureRect = { x = 95, y = 0, width = 27, height = 31 }, 
				spriteSourceSize = { width = 27, height = 31 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end