module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- For more details, see http://developer.anscamobile.com/reference/sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "jump.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 63 }, 
				textureRect = { x = 280, y = 1, width = 54, height = 63 }, 
				spriteSourceSize = { width = 54, height = 63 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "stand.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 65 }, 
				textureRect = { x = 0, y = 0, width = 54, height = 65 }, 
				spriteSourceSize = { width = 54, height = 65 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "throw1.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 59 }, 
				textureRect = { x = 333, y = 0, width = 54, height = 59 }, 
				spriteSourceSize = { width = 54, height = 59 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "throw2.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 61 }, 
				textureRect = { x = 385, y = 4, width = 54, height = 61 }, 
				spriteSourceSize = { width = 54, height = 61 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "throw3.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 60 }, 
				textureRect = { x = 440, y = 4, width = 56, height = 60 }, 
				spriteSourceSize = { width = 56, height = 60 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "walk0.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 65 }, 
				textureRect = { x = 56, y = 0, width = 54, height = 65 }, 
				spriteSourceSize = { width = 54, height = 65 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "walk1.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 64 }, 
				textureRect = { x = 112, y = 0, width = 54, height = 64 }, 
				spriteSourceSize = { width = 54, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "walk2.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 65 }, 
				textureRect = { x = 168, y = 0, width = 54, height = 65 }, 
				spriteSourceSize = { width = 54, height = 65 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "walk3.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 64 }, 
				textureRect = { x = 224, y = 0, width = 54, height = 64 }, 
				spriteSourceSize = { width = 54, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end